from __future__ import annotations

from core.settings_profiles import LORA_AUTO_MANAGED_SETTING_KEYS

LORA_RETRIEVAL_INDEX_SCHEMA = "ai_subtitle_studio.lora_retrieval_index.v1"
LORA_RETRIEVAL_SCORE_MODEL = "hybrid_hash_vector_bm25_context_facet_quality_bucket_v3"
LORA_RETRIEVAL_HASH_DIM = 768
LORA_RETRIEVAL_MAX_TEXT_CHARS = 2400
LORA_QUERY_CACHE_MAX = 96

SCORE_POINT_WEIGHTS = {
    "vector": 44.0,
    "bm25": 9.0,
    "bm25_cap": 24.0,
    "overlap": 8.0,
    "quality": 8.0,
    "recency_cap": 2.5,
}
FACET_POINT_WEIGHTS = {
    "scene": 4.0,
    "topic": 5.0,
    "mic_type": 2.0,
    "noise_level": 2.0,
}
LIST_FACET_POINT_WEIGHTS = {
    "noise_sources": (1.1, 3.3),
    "training_focus": (0.65, 2.6),
    "topic_terms": (0.35, 2.1),
}

INDEX_JSONL_SOURCE_KEYS = (
    "truth_table",
    "excluded_parentheticals",
    "setting_trials",
    "prompt_trials",
    "voice_lora_bridge",
    "stt1_whisper_adapter_dataset",
    "text_lora_dataset",
    "text_lora_corpus",
    "audio_preset_lora",
    "multimodal_lora_context",
    "deep_policy_events",
)
INDEX_JSON_SOURCE_KEYS = (
    "learned_split_rules",
    "learned_line_break_rules",
    "best_settings",
    "text_lora_manifest",
    "text_lora_corpus_manifest",
    "text_lora_training_plan",
    "voice_lora_profile_manifest",
    "voice_lora_training_plan",
    "voice_lora_dataset_manifest",
    "stt1_whisper_adapter_dataset_manifest",
    "stt1_whisper_adapter_training_plan",
    "stt1_whisper_adapter_runtime_manifest",
)
RUNTIME_SETTING_KEYS = set(LORA_AUTO_MANAGED_SETTING_KEYS) | {
    "selected_audio_ai",
    "selected_vad",
    "selected_whisper_model",
    "selected_whisper_model_secondary",
    "stt_ensemble_enabled",
    "stt_ensemble_llm_judge_enabled",
    "stt_candidate_scoring_enabled",
    "stt_low_score_recheck_enabled",
    "stt_low_score_recheck_threshold",
    "stt_quality_preset",
    "subtitle_quality_enabled",
    "subtitle_quality_auto_check_after_generate",
    "subtitle_quality_auto_correct_enabled",
    "editor_lora_runtime_enabled",
    "correction_memory_enabled",
    "wrong_answer_memory_enabled",
    "continuous_threshold",
    "gap_push_rate",
    "gap_pull_rate",
    "single_subtitle_end",
    "split_length_threshold",
    "subtitle_target_line_count",
    "subtitle_target_line_count_auto_enabled",
    "sub_min_duration",
    "sub_max_duration",
    "sub_max_cps",
    "sub_dedup_window",
    "sub_gap_break_sec",
    "selected_model",
    "selected_llm_provider",
    "llm_threads_auto_enabled",
    "llm_workers_auto_enabled",
    "llm_threads_resource_max",
    "roughcut_llm_model",
    "roughcut_llm_provider",
    "roughcut_llm_threads_auto_enabled",
    "roughcut_llm_threads_resource_max",
    "roughcut_llm_rows_auto_enabled",
    "roughcut_llm_rows_lora_enabled",
    "roughcut_llm_rows_lora_blend",
    "roughcut_llm_rows_exploration_rate",
    "roughcut_llm_max_context_rows",
    "roughcut_llm_chunk_rows",
    "roughcut_llm_lookahead_rows",
    "roughcut_llm_context_min_rows",
    "roughcut_llm_context_max_rows",
    "roughcut_llm_chunk_min_rows",
    "roughcut_llm_chunk_max_rows",
    "roughcut_llm_lookahead_min_rows",
    "roughcut_llm_lookahead_max_rows",
    "review_auto_correct_apply_threshold",
    "review_auto_correct_min_improvement",
    "review_recheck_buffer_sec",
    "vad_post_stt_align_enabled",
    "vad_threshold",
    "vad_min_speech",
    "vad_min_silence",
    "vad_speech_pad",
    "vad_window_size",
    "ff_chunk",
    "ff_threads",
    "ff_ac",
    "ff_ar",
    "ff_hp",
    "ff_lp",
    "ff_nf",
    "ff_dynaudnorm_m",
    "ff_dynaudnorm_p",
    "ff_treble_boost",
    "df_hp",
    "df_eq_g",
    "df_comp_th",
    "df_vol",
    "df_atten_lim",
    "w_df_no_speech",
    "w_df_logprob",
    "w_df_comp",
    "w_df_temp_max",
    "w_none_no_speech",
    "w_none_logprob",
    "w_none_comp",
    "w_none_temp_max",
    "w_beam_size",
    "w_patience",
    "w_length_penalty",
    "cut_boundary_level",
    "scan_cut_boundary_level",
    "scan_cut_auto_sample_step_sec",
    "scan_cut_audio_gain_enabled",
    "scan_cut_audio_gain_threshold_db",
}
