# Version: 03.14.00
# Phase: PHASE2
"""Curated/default audio preset data for AI Subtitle Studio."""

from __future__ import annotations

from core.runtime import config


def _stt1_model() -> str:
    return "mlx-community/whisper-large-v3-mlx" if config.IS_MAC else "large-v3"


def _stt2_model() -> str:
    return "youngouk/ghost613-turbo-korean-4bit-mlx" if config.IS_MAC else "ghost613/faster-whisper-large-v3-turbo-korean"


def _roughcut_llm(model_name: str) -> dict:
    enabled = bool(model_name and "사용 안함" not in model_name)
    return {
        "roughcut_llm_enabled": enabled,
        "roughcut_llm_use_override": enabled,
        "roughcut_llm_provider": "ollama" if enabled else "none",
        "roughcut_llm_model": model_name if enabled else "사용 안함",
    }


def _full_stack_recommendation(
    *,
    cut_level: str,
    preprocess_model: str,
    audio_model: str,
    stt1_model: str,
    stt2_model: str,
    vad_model: str,
    subtitle_llm: str,
    roughcut_llm_model: str,
) -> dict:
    cut_level = str(cut_level or "off").lower()
    if cut_level == "high":
        cut_level = "medium"
    enabled = str(cut_level or "off").lower() != "off"
    return {
        "audio_preset_recommended_cut_boundary": cut_level,
        "audio_preset_recommended_preprocess_model": preprocess_model,
        "audio_preset_recommended_audio_model": audio_model,
        "audio_preset_recommended_stt1": stt1_model,
        "audio_preset_recommended_stt2": stt2_model,
        "audio_preset_recommended_vad": vad_model,
        "audio_preset_recommended_subtitle_llm": subtitle_llm,
        "audio_preset_recommended_roughcut_llm": roughcut_llm_model,
        "cut_boundary_level": cut_level,
        "scan_cut_boundary_level": cut_level,
        "scan_cut_level": cut_level,
        "cut_boundary_detection_enabled": enabled,
        "scan_cut_enabled": enabled,
        "scan_cut_auto_enabled": enabled,
        "cut_boundary_enabled": enabled,
        "selected_audio_ai": audio_model,
        "selected_vad": vad_model,
        "selected_whisper_model": stt1_model,
        "selected_whisper_model_secondary": stt2_model,
        "stt_ensemble_enabled": True,
        "stt_ensemble_llm_judge_enabled": True,
        "selected_model": subtitle_llm,
        **_roughcut_llm(roughcut_llm_model),
    }

CURATED_AUDIO_PRESET_SPECS = {
    "실내-마이크유": {
        "base": "실내일반",
        "description": "실내 수음 + 외부 마이크 기준의 균형형 프리셋",
        "stack": _full_stack_recommendation(
            cut_level="medium",
            preprocess_model="ffmpeg-balanced",
            audio_model="deepfilter",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="silero",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
    "실내-마이크무": {
        "base": "브이로그실내",
        "fallbacks": ["스마트폰", "실내일반", "마이크 없음/풀속도"],
        "description": "실내 수음 + 내장 마이크 기준의 보정형 프리셋",
        "overrides": {
            "ff_nf": -27,
            "ff_dynaudnorm_m": 14.0,
            "ff_treble_boost": 1.5,
        },
        "stack": _full_stack_recommendation(
            cut_level="medium",
            preprocess_model="ffmpeg-voice-cleanup",
            audio_model="deepfilter",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="silero",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
    "실외-마이크유": {
        "base": "야외",
        "description": "실외 수음 + 외부 마이크 기준의 강한 노이즈 대응 프리셋",
        "stack": _full_stack_recommendation(
            cut_level="high",
            preprocess_model="ffmpeg-outdoor-strong",
            audio_model="clearvoice",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="ten_vad",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
    "실외-마이크무": {
        "base": "스마트폰",
        "fallbacks": ["야외", "마이크 없음/풀속도"],
        "description": "실외 수음 + 내장 마이크 기준의 강한 보정 프리셋",
        "overrides": {
            "ff_nf": -30,
            "ff_dynaudnorm_m": 18.0,
            "ff_treble_boost": 3.0,
        },
        "stack": _full_stack_recommendation(
            cut_level="high",
            preprocess_model="ffmpeg-outdoor-strong",
            audio_model="clearvoice",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="ten_vad",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
    "차안-마이크유": {
        "base": "차량",
        "fallbacks": ["실내일반"],
        "description": "차량 내부 + 외부 마이크 기준의 저역/엔진 소음 대응 프리셋",
        "stack": _full_stack_recommendation(
            cut_level="high",
            preprocess_model="ffmpeg-car-lowcut",
            audio_model="clearvoice",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="ten_vad",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
    "차안-마이크무": {
        "base": "차량",
        "fallbacks": ["스마트폰", "실내일반"],
        "description": "차량 내부 + 내장 마이크 기준의 강한 저역/노이즈 보정 프리셋",
        "overrides": {
            "ff_hp": 150,
            "ff_nf": -30,
            "ff_dynaudnorm_m": 18.0,
            "ff_treble_boost": 2.5,
        },
        "stack": _full_stack_recommendation(
            cut_level="high",
            preprocess_model="ffmpeg-car-lowcut",
            audio_model="clearvoice",
            stt1_model=_stt1_model(),
            stt2_model=_stt2_model(),
            vad_model="ten_vad",
            subtitle_llm="gemma4:e4b",
            roughcut_llm_model="exaone3.5:7.8b",
        ),
    },
}


DEFAULT_AUDIO_APPLY_DATA = {
    "selected_audio_ai": "deepfilter",
    "selected_vad": "silero",
    "vad_threshold": 0.5,
    "vad_min_speech": 0.25,
    "vad_min_silence": 2.0,
    "vad_speech_pad": 0.1,
    "vad_window_size": 512,
    "df_hp": 100,
    "df_eq_g": 8,
    "df_comp_th": -28,
    "df_vol": 3.5,
    "df_atten_lim": 100,
    "w_df_no_speech": 0.4,
    "w_df_logprob": -2.5,
    "w_df_comp": 2.4,
    "w_df_temp_max": 0.8,
    "none_hp": 80,
    "none_lp": 3000,
    "none_nf": -25,
    "none_target": -14,
    "none_comp_th": -28,
    "none_vol": 4.0,
    "w_none_no_speech": 0.85,
    "w_none_logprob": -1.0,
    "w_none_comp": 1.6,
    "w_none_temp_max": 0.4,
    "w_beam_size": 5,
    "w_patience": 1.0,
    "w_length_penalty": 1.0,
    "io_workers": 6,
    "ff_threads": 0,
    "ff_ac": 1,
    "ff_ar": 16000,
    "ff_hp": 200,
    "ff_lp": 3000,
    "ff_nf": -25,
    "ff_chunk": 30,
    "ff_dynaudnorm_m": 10.0,
    "ff_dynaudnorm_p": 0.95,
    "ff_treble_boost": 0.0,
    "continuous_threshold": 2.0,
    "gap_pull_rate": 0.3,
    "gap_push_rate": 0.7,
    "single_subtitle_end": 0.2,
    "split_length_threshold": 10,
    "sub_min_duration": 0.2,
    "sub_max_duration": 6.0,
    "sub_max_cps": 12,
    "sub_dedup_window": 0.5,
    "sub_gap_break_sec": 1.5,
    "prefetch_ahead": 3,
    "stt_parallel_level": 3,
    "video_ui_interval_ms": 33,
}


DEFAULT_AUDIO_PRESETS: dict[str, dict] = {'마이크 없음/풀속도': {'description': 'STT 속도 최우선, AudioAI/VAD 생략',
                'settings': {'vad_threshold': 0.42,
                             'vad_min_speech': 0.22,
                             'vad_min_silence': 1.6,
                             'vad_speech_pad': 0.12,
                             'vad_window_size': 512,
                             'df_hp': 100,
                             'df_eq_g': 8,
                             'df_comp_th': -28,
                             'df_vol': 3.5,
                             'df_atten_lim': 100,
                             'w_df_no_speech': 0.38,
                             'w_df_logprob': -2.4,
                             'w_df_comp': 2.35,
                             'w_df_temp_max': 0.4,
                             'none_hp': 120,
                             'none_lp': 3600,
                             'none_nf': -28,
                             'none_target': -14,
                             'none_comp_th': -24,
                             'none_vol': 5.0,
                             'w_none_no_speech': 0.9,
                             'w_none_logprob': -1.15,
                             'w_none_comp': 1.55,
                             'w_none_temp_max': 0.0,
                             'w_beam_size': 5,
                             'w_patience': 1.0,
                             'w_length_penalty': 1.0,
                             'io_workers': 12,
                             'llm_threads': 6,
                             'ff_threads': 0,
                             'ff_ac': 1,
                             'ff_ar': 16000,
                             'ff_hp': 110,
                             'ff_lp': 3800,
                             'ff_nf': -28,
                             'ff_chunk': 20,
                             'ff_dynaudnorm_m': 14.0,
                             'ff_dynaudnorm_p': 0.97,
                             'ff_treble_boost': 2.0,
                             'continuous_threshold': 2.0,
                             'gap_pull_rate': 0.18,
                             'gap_push_rate': 0.82,
                             'single_subtitle_end': 0.2,
                             'split_length_threshold': 10,
                             'sub_min_duration': 0.3,
                             'sub_max_cps': 12,
                             'sub_dedup_window': 0.5,
                             'sub_gap_break_sec': 1.5,
                             'prefetch_ahead': 3,
                             'stt_parallel_level': 3,
                             'video_ui_interval_ms': 33,
                             'vad_threshold_disabled': False,
                             'vad_min_speech_disabled': False,
                             'vad_min_silence_disabled': False,
                             'vad_speech_pad_disabled': False,
                             'vad_window_size_disabled': False,
                             'df_hp_disabled': False,
                             'df_eq_g_disabled': False,
                             'df_comp_th_disabled': False,
                             'df_vol_disabled': False,
                             'df_atten_lim_disabled': False,
                             'w_df_no_speech_disabled': False,
                             'w_df_logprob_disabled': False,
                             'w_df_comp_disabled': False,
                             'w_df_temp_max_disabled': False,
                             'none_hp_disabled': False,
                             'none_lp_disabled': False,
                             'none_nf_disabled': False,
                             'none_target_disabled': False,
                             'none_comp_th_disabled': False,
                             'none_vol_disabled': False,
                             'w_none_no_speech_disabled': False,
                             'w_none_logprob_disabled': False,
                             'w_none_comp_disabled': False,
                             'w_none_temp_max_disabled': False,
                             'w_beam_size_disabled': False,
                             'w_patience_disabled': False,
                             'w_length_penalty_disabled': False,
                             'io_workers_disabled': False,
                             'llm_threads_disabled': False,
                             'ff_threads_disabled': False,
                             'ff_ac_disabled': False,
                             'ff_ar_disabled': False,
                             'ff_hp_disabled': False,
                             'ff_lp_disabled': False,
                             'ff_nf_disabled': False,
                             'ff_chunk_disabled': False,
                             'ff_dynaudnorm_m_disabled': False,
                             'ff_dynaudnorm_p_disabled': False,
                             'ff_treble_boost_disabled': False,
                             'continuous_threshold_disabled': False,
                             'gap_pull_rate_disabled': False,
                             'gap_push_rate_disabled': False,
                             'single_subtitle_end_disabled': False,
                             'split_length_threshold_disabled': False,
                             'sub_min_duration_disabled': False,
                             'sub_max_cps_disabled': False,
                             'sub_dedup_window_disabled': False,
                             'sub_gap_break_sec_disabled': False,
                             'prefetch_ahead_disabled': False,
                             'stt_parallel_level_disabled': False,
                             'video_ui_interval_ms_disabled': False}},
 '스튜디오': {'description': '깨끗한 수음, 품질 우선',
          'settings': {'vad_threshold': 0.48,
                       'vad_min_speech': 0.22,
                       'vad_min_silence': 1.7,
                       'vad_speech_pad': 0.12,
                       'vad_window_size': 512,
                       'df_hp': 80,
                       'df_eq_g': 5,
                       'df_comp_th': -30,
                       'df_vol': 3.0,
                       'df_atten_lim': 100,
                       'w_df_no_speech': 0.32,
                       'w_df_logprob': -2.2,
                       'w_df_comp': 2.4,
                       'w_df_temp_max': 0.4,
                       'none_hp': 90,
                       'none_lp': 3200,
                       'none_nf': -32,
                       'none_target': -14,
                       'none_comp_th': -28,
                       'none_vol': 4.0,
                       'w_none_no_speech': 0.82,
                       'w_none_logprob': -1.0,
                       'w_none_comp': 1.6,
                       'w_none_temp_max': 0.0,
                       'w_beam_size': 6,
                       'w_patience': 1.2,
                       'w_length_penalty': 1.0,
                       'io_workers': 10,
                       'llm_threads': 6,
                       'ff_threads': 0,
                       'ff_ac': 1,
                       'ff_ar': 16000,
                       'ff_hp': 90,
                       'ff_lp': 3200,
                       'ff_nf': -32,
                       'ff_chunk': 25,
                       'ff_dynaudnorm_m': 10.0,
                       'ff_dynaudnorm_p': 0.95,
                       'ff_treble_boost': 0.0,
                       'continuous_threshold': 2.0,
                       'gap_pull_rate': 0.18,
                       'gap_push_rate': 0.82,
                       'single_subtitle_end': 0.2,
                       'split_length_threshold': 10,
                       'sub_min_duration': 0.3,
                       'sub_max_cps': 12,
                       'sub_dedup_window': 0.5,
                       'sub_gap_break_sec': 1.5,
                       'prefetch_ahead': 3,
                       'stt_parallel_level': 3,
                       'video_ui_interval_ms': 33,
                       'vad_threshold_disabled': False,
                       'vad_min_speech_disabled': False,
                       'vad_min_silence_disabled': False,
                       'vad_speech_pad_disabled': False,
                       'vad_window_size_disabled': False,
                       'df_hp_disabled': False,
                       'df_eq_g_disabled': False,
                       'df_comp_th_disabled': False,
                       'df_vol_disabled': False,
                       'df_atten_lim_disabled': False,
                       'w_df_no_speech_disabled': False,
                       'w_df_logprob_disabled': False,
                       'w_df_comp_disabled': False,
                       'w_df_temp_max_disabled': False,
                       'none_hp_disabled': False,
                       'none_lp_disabled': False,
                       'none_nf_disabled': False,
                       'none_target_disabled': False,
                       'none_comp_th_disabled': False,
                       'none_vol_disabled': False,
                       'w_none_no_speech_disabled': False,
                       'w_none_logprob_disabled': False,
                       'w_none_comp_disabled': False,
                       'w_none_temp_max_disabled': False,
                       'w_beam_size_disabled': False,
                       'w_patience_disabled': False,
                       'w_length_penalty_disabled': False,
                       'io_workers_disabled': False,
                       'llm_threads_disabled': False,
                       'ff_threads_disabled': False,
                       'ff_ac_disabled': False,
                       'ff_ar_disabled': False,
                       'ff_hp_disabled': False,
                       'ff_lp_disabled': False,
                       'ff_nf_disabled': False,
                       'ff_chunk_disabled': False,
                       'ff_dynaudnorm_m_disabled': False,
                       'ff_dynaudnorm_p_disabled': False,
                       'ff_treble_boost_disabled': False,
                       'continuous_threshold_disabled': False,
                       'gap_pull_rate_disabled': False,
                       'gap_push_rate_disabled': False,
                       'single_subtitle_end_disabled': False,
                       'split_length_threshold_disabled': False,
                       'sub_min_duration_disabled': False,
                       'sub_max_cps_disabled': False,
                       'sub_dedup_window_disabled': False,
                       'sub_gap_break_sec_disabled': False,
                       'prefetch_ahead_disabled': False,
                       'stt_parallel_level_disabled': False,
                       'video_ui_interval_ms_disabled': False}},
 '실내일반': {'description': '일반 실내 대화 균형',
          'settings': {'vad_threshold': 0.43,
                       'vad_min_speech': 0.22,
                       'vad_min_silence': 1.7,
                       'vad_speech_pad': 0.12,
                       'vad_window_size': 512,
                       'df_hp': 100,
                       'df_eq_g': 7,
                       'df_comp_th': -28,
                       'df_vol': 3.5,
                       'df_atten_lim': 100,
                       'w_df_no_speech': 0.38,
                       'w_df_logprob': -2.4,
                       'w_df_comp': 2.35,
                       'w_df_temp_max': 0.4,
                       'none_hp': 90,
                       'none_lp': 3200,
                       'none_nf': -32,
                       'none_target': -14,
                       'none_comp_th': -28,
                       'none_vol': 4.0,
                       'w_none_no_speech': 0.82,
                       'w_none_logprob': -1.0,
                       'w_none_comp': 1.6,
                       'w_none_temp_max': 0.0,
                       'w_beam_size': 6,
                       'w_patience': 1.2,
                       'w_length_penalty': 1.0,
                       'io_workers': 10,
                       'llm_threads': 6,
                       'ff_threads': 0,
                       'ff_ac': 1,
                       'ff_ar': 16000,
                       'ff_hp': 90,
                       'ff_lp': 3200,
                       'ff_nf': -32,
                       'ff_chunk': 25,
                       'ff_dynaudnorm_m': 10.0,
                       'ff_dynaudnorm_p': 0.95,
                       'ff_treble_boost': 0.0,
                       'continuous_threshold': 2.0,
                       'gap_pull_rate': 0.18,
                       'gap_push_rate': 0.82,
                       'single_subtitle_end': 0.2,
                       'split_length_threshold': 10,
                       'sub_min_duration': 0.3,
                       'sub_max_cps': 12,
                       'sub_dedup_window': 0.5,
                       'sub_gap_break_sec': 1.5,
                       'prefetch_ahead': 3,
                       'stt_parallel_level': 3,
                       'video_ui_interval_ms': 33,
                       'vad_threshold_disabled': False,
                       'vad_min_speech_disabled': False,
                       'vad_min_silence_disabled': False,
                       'vad_speech_pad_disabled': False,
                       'vad_window_size_disabled': False,
                       'df_hp_disabled': False,
                       'df_eq_g_disabled': False,
                       'df_comp_th_disabled': False,
                       'df_vol_disabled': False,
                       'df_atten_lim_disabled': False,
                       'w_df_no_speech_disabled': False,
                       'w_df_logprob_disabled': False,
                       'w_df_comp_disabled': False,
                       'w_df_temp_max_disabled': False,
                       'none_hp_disabled': False,
                       'none_lp_disabled': False,
                       'none_nf_disabled': False,
                       'none_target_disabled': False,
                       'none_comp_th_disabled': False,
                       'none_vol_disabled': False,
                       'w_none_no_speech_disabled': False,
                       'w_none_logprob_disabled': False,
                       'w_none_comp_disabled': False,
                       'w_none_temp_max_disabled': False,
                       'w_beam_size_disabled': False,
                       'w_patience_disabled': False,
                       'w_length_penalty_disabled': False,
                       'io_workers_disabled': False,
                       'llm_threads_disabled': False,
                       'ff_threads_disabled': False,
                       'ff_ac_disabled': False,
                       'ff_ar_disabled': False,
                       'ff_hp_disabled': False,
                       'ff_lp_disabled': False,
                       'ff_nf_disabled': False,
                       'ff_chunk_disabled': False,
                       'ff_dynaudnorm_m_disabled': False,
                       'ff_dynaudnorm_p_disabled': False,
                       'ff_treble_boost_disabled': False,
                       'continuous_threshold_disabled': False,
                       'gap_pull_rate_disabled': False,
                       'gap_push_rate_disabled': False,
                       'single_subtitle_end_disabled': False,
                       'split_length_threshold_disabled': False,
                       'sub_min_duration_disabled': False,
                       'sub_max_cps_disabled': False,
                       'sub_dedup_window_disabled': False,
                       'sub_gap_break_sec_disabled': False,
                       'prefetch_ahead_disabled': False,
                       'stt_parallel_level_disabled': False,
                       'video_ui_interval_ms_disabled': False}},
 '인터뷰': {'description': '말소리 중심, 문장 단위 유지',
         'settings': {'vad_threshold': 0.4,
                      'vad_min_speech': 0.18,
                      'vad_min_silence': 2.1,
                      'vad_speech_pad': 0.12,
                      'vad_window_size': 512,
                      'df_hp': 90,
                      'df_eq_g': 8,
                      'df_comp_th': -30,
                      'df_vol': 3.5,
                      'df_atten_lim': 100,
                      'w_df_no_speech': 0.34,
                      'w_df_logprob': -2.6,
                      'w_df_comp': 2.4,
                      'w_df_temp_max': 0.5,
                      'none_hp': 90,
                      'none_lp': 3200,
                      'none_nf': -32,
                      'none_target': -14,
                      'none_comp_th': -28,
                      'none_vol': 4.0,
                      'w_none_no_speech': 0.82,
                      'w_none_logprob': -1.0,
                      'w_none_comp': 1.6,
                      'w_none_temp_max': 0.0,
                      'w_beam_size': 6,
                      'w_patience': 1.2,
                      'w_length_penalty': 1.0,
                      'io_workers': 10,
                      'llm_threads': 6,
                      'ff_threads': 0,
                      'ff_ac': 1,
                      'ff_ar': 16000,
                      'ff_hp': 90,
                      'ff_lp': 3200,
                      'ff_nf': -32,
                      'ff_chunk': 25,
                      'ff_dynaudnorm_m': 10.0,
                      'ff_dynaudnorm_p': 0.95,
                      'ff_treble_boost': 0.0,
                      'continuous_threshold': 2.0,
                      'gap_pull_rate': 0.18,
                      'gap_push_rate': 0.82,
                      'single_subtitle_end': 0.2,
                      'split_length_threshold': 10,
                      'sub_min_duration': 0.3,
                      'sub_max_cps': 12,
                      'sub_dedup_window': 0.5,
                      'sub_gap_break_sec': 1.5,
                      'prefetch_ahead': 3,
                      'stt_parallel_level': 3,
                      'video_ui_interval_ms': 33,
                      'vad_threshold_disabled': False,
                      'vad_min_speech_disabled': False,
                      'vad_min_silence_disabled': False,
                      'vad_speech_pad_disabled': False,
                      'vad_window_size_disabled': False,
                      'df_hp_disabled': False,
                      'df_eq_g_disabled': False,
                      'df_comp_th_disabled': False,
                      'df_vol_disabled': False,
                      'df_atten_lim_disabled': False,
                      'w_df_no_speech_disabled': False,
                      'w_df_logprob_disabled': False,
                      'w_df_comp_disabled': False,
                      'w_df_temp_max_disabled': False,
                      'none_hp_disabled': False,
                      'none_lp_disabled': False,
                      'none_nf_disabled': False,
                      'none_target_disabled': False,
                      'none_comp_th_disabled': False,
                      'none_vol_disabled': False,
                      'w_none_no_speech_disabled': False,
                      'w_none_logprob_disabled': False,
                      'w_none_comp_disabled': False,
                      'w_none_temp_max_disabled': False,
                      'w_beam_size_disabled': False,
                      'w_patience_disabled': False,
                      'w_length_penalty_disabled': False,
                      'io_workers_disabled': False,
                      'llm_threads_disabled': False,
                      'ff_threads_disabled': False,
                      'ff_ac_disabled': False,
                      'ff_ar_disabled': False,
                      'ff_hp_disabled': False,
                      'ff_lp_disabled': False,
                      'ff_nf_disabled': False,
                      'ff_chunk_disabled': False,
                      'ff_dynaudnorm_m_disabled': False,
                      'ff_dynaudnorm_p_disabled': False,
                      'ff_treble_boost_disabled': False,
                      'continuous_threshold_disabled': False,
                      'gap_pull_rate_disabled': False,
                      'gap_push_rate_disabled': False,
                      'single_subtitle_end_disabled': False,
                      'split_length_threshold_disabled': False,
                      'sub_min_duration_disabled': False,
                      'sub_max_cps_disabled': False,
                      'sub_dedup_window_disabled': False,
                      'sub_gap_break_sec_disabled': False,
                      'prefetch_ahead_disabled': False,
                      'stt_parallel_level_disabled': False,
                      'video_ui_interval_ms_disabled': False}},
 '브이로그실내': {'description': '실내 이동/생활 소음 대응',
            'settings': {'vad_threshold': 0.4,
                         'vad_min_speech': 0.22,
                         'vad_min_silence': 1.4,
                         'vad_speech_pad': 0.12,
                         'vad_window_size': 512,
                         'df_hp': 120,
                         'df_eq_g': 10,
                         'df_comp_th': -28,
                         'df_vol': 4.2,
                         'df_atten_lim': 100,
                         'w_df_no_speech': 0.52,
                         'w_df_logprob': -2.6,
                         'w_df_comp': 2.45,
                         'w_df_temp_max': 0.5,
                         'none_hp': 90,
                         'none_lp': 3200,
                         'none_nf': -32,
                         'none_target': -14,
                         'none_comp_th': -28,
                         'none_vol': 4.0,
                         'w_none_no_speech': 0.82,
                         'w_none_logprob': -1.0,
                         'w_none_comp': 1.6,
                         'w_none_temp_max': 0.0,
                         'w_beam_size': 6,
                         'w_patience': 1.2,
                         'w_length_penalty': 1.0,
                         'io_workers': 10,
                         'llm_threads': 6,
                         'ff_threads': 0,
                         'ff_ac': 1,
                         'ff_ar': 16000,
                         'ff_hp': 100,
                         'ff_lp': 5200,
                         'ff_nf': -30,
                         'ff_chunk': 25,
                         'ff_dynaudnorm_m': 12.0,
                         'ff_dynaudnorm_p': 0.96,
                         'ff_treble_boost': 1.5,
                         'continuous_threshold': 2.0,
                         'gap_pull_rate': 0.18,
                         'gap_push_rate': 0.82,
                         'single_subtitle_end': 0.2,
                         'split_length_threshold': 10,
                         'sub_min_duration': 0.3,
                         'sub_max_cps': 12,
                         'sub_dedup_window': 0.5,
                         'sub_gap_break_sec': 1.5,
                         'prefetch_ahead': 3,
                         'stt_parallel_level': 3,
                         'video_ui_interval_ms': 33,
                         'vad_threshold_disabled': False,
                         'vad_min_speech_disabled': False,
                         'vad_min_silence_disabled': False,
                         'vad_speech_pad_disabled': False,
                         'vad_window_size_disabled': False,
                         'df_hp_disabled': False,
                         'df_eq_g_disabled': False,
                         'df_comp_th_disabled': False,
                         'df_vol_disabled': False,
                         'df_atten_lim_disabled': False,
                         'w_df_no_speech_disabled': False,
                         'w_df_logprob_disabled': False,
                         'w_df_comp_disabled': False,
                         'w_df_temp_max_disabled': False,
                         'none_hp_disabled': False,
                         'none_lp_disabled': False,
                         'none_nf_disabled': False,
                         'none_target_disabled': False,
                         'none_comp_th_disabled': False,
                         'none_vol_disabled': False,
                         'w_none_no_speech_disabled': False,
                         'w_none_logprob_disabled': False,
                         'w_none_comp_disabled': False,
                         'w_none_temp_max_disabled': False,
                         'w_beam_size_disabled': False,
                         'w_patience_disabled': False,
                         'w_length_penalty_disabled': False,
                         'io_workers_disabled': False,
                         'llm_threads_disabled': False,
                         'ff_threads_disabled': False,
                         'ff_ac_disabled': False,
                         'ff_ar_disabled': False,
                         'ff_hp_disabled': False,
                         'ff_lp_disabled': False,
                         'ff_nf_disabled': False,
                         'ff_chunk_disabled': False,
                         'ff_dynaudnorm_m_disabled': False,
                         'ff_dynaudnorm_p_disabled': False,
                         'ff_treble_boost_disabled': False,
                         'continuous_threshold_disabled': False,
                         'gap_pull_rate_disabled': False,
                         'gap_push_rate_disabled': False,
                         'single_subtitle_end_disabled': False,
                         'split_length_threshold_disabled': False,
                         'sub_min_duration_disabled': False,
                         'sub_max_cps_disabled': False,
                         'sub_dedup_window_disabled': False,
                         'sub_gap_break_sec_disabled': False,
                         'prefetch_ahead_disabled': False,
                         'stt_parallel_level_disabled': False,
                         'video_ui_interval_ms_disabled': False,
                         'df_lp': 5600,
                         'df_nf': -30}},
 '야외': {'description': '바람/차량/환경음 많은 상황',
        'settings': {'vad_threshold': 0.55,
                     'vad_min_speech': 0.28,
                     'vad_min_silence': 1.2,
                     'vad_speech_pad': 0.12,
                     'vad_window_size': 512,
                     'df_hp': 170,
                     'df_eq_g': 12,
                     'df_comp_th': -24,
                     'df_vol': 4.8,
                     'df_atten_lim': 100,
                     'w_df_no_speech': 0.62,
                     'w_df_logprob': -2.7,
                     'w_df_comp': 2.55,
                     'w_df_temp_max': 0.3,
                     'none_hp': 120,
                     'none_lp': 3800,
                     'none_nf': -28,
                     'none_target': -14,
                     'none_comp_th': -24,
                     'none_vol': 5.0,
                     'w_none_no_speech': 0.82,
                     'w_none_logprob': -1.0,
                     'w_none_comp': 1.6,
                     'w_none_temp_max': 0.0,
                     'w_beam_size': 6,
                     'w_patience': 1.2,
                     'w_length_penalty': 1.0,
                     'io_workers': 10,
                     'llm_threads': 6,
                     'ff_threads': 0,
                     'ff_ac': 1,
                     'ff_ar': 16000,
                     'ff_hp': 120,
                     'ff_lp': 4200,
                     'ff_nf': -26,
                     'ff_chunk': 25,
                     'ff_dynaudnorm_m': 16.0,
                     'ff_dynaudnorm_p': 0.97,
                     'ff_treble_boost': 3.0,
                     'continuous_threshold': 2.0,
                     'gap_pull_rate': 0.18,
                     'gap_push_rate': 0.82,
                     'single_subtitle_end': 0.2,
                     'split_length_threshold': 10,
                     'sub_min_duration': 0.3,
                     'sub_max_cps': 12,
                     'sub_dedup_window': 0.5,
                     'sub_gap_break_sec': 1.5,
                     'prefetch_ahead': 3,
                     'stt_parallel_level': 3,
                     'video_ui_interval_ms': 33,
                     'vad_threshold_disabled': False,
                     'vad_min_speech_disabled': False,
                     'vad_min_silence_disabled': False,
                     'vad_speech_pad_disabled': False,
                     'vad_window_size_disabled': False,
                     'df_hp_disabled': False,
                     'df_eq_g_disabled': False,
                     'df_comp_th_disabled': False,
                     'df_vol_disabled': False,
                     'df_atten_lim_disabled': False,
                     'w_df_no_speech_disabled': False,
                     'w_df_logprob_disabled': False,
                     'w_df_comp_disabled': False,
                     'w_df_temp_max_disabled': False,
                     'none_hp_disabled': False,
                     'none_lp_disabled': False,
                     'none_nf_disabled': False,
                     'none_target_disabled': False,
                     'none_comp_th_disabled': False,
                     'none_vol_disabled': False,
                     'w_none_no_speech_disabled': False,
                     'w_none_logprob_disabled': False,
                     'w_none_comp_disabled': False,
                     'w_none_temp_max_disabled': False,
                     'w_beam_size_disabled': False,
                     'w_patience_disabled': False,
                     'w_length_penalty_disabled': False,
                     'io_workers_disabled': False,
                     'llm_threads_disabled': False,
                     'ff_threads_disabled': False,
                     'ff_ac_disabled': False,
                     'ff_ar_disabled': False,
                     'ff_hp_disabled': False,
                     'ff_lp_disabled': False,
                     'ff_nf_disabled': False,
                     'ff_chunk_disabled': False,
                     'ff_dynaudnorm_m_disabled': False,
                     'ff_dynaudnorm_p_disabled': False,
                     'ff_treble_boost_disabled': False,
                     'continuous_threshold_disabled': False,
                     'gap_pull_rate_disabled': False,
                     'gap_push_rate_disabled': False,
                     'single_subtitle_end_disabled': False,
                     'split_length_threshold_disabled': False,
                     'sub_min_duration_disabled': False,
                     'sub_max_cps_disabled': False,
                     'sub_dedup_window_disabled': False,
                     'sub_gap_break_sec_disabled': False,
                     'prefetch_ahead_disabled': False,
                     'stt_parallel_level_disabled': False,
                     'video_ui_interval_ms_disabled': False,
                     'df_lp': 5200,
                     'df_nf': -26}},
 '강연': {'description': '긴 문장, 울림 있는 공간',
        'settings': {'vad_threshold': 0.47,
                     'vad_min_speech': 0.28,
                     'vad_min_silence': 2.5,
                     'vad_speech_pad': 0.12,
                     'vad_window_size': 512,
                     'df_hp': 90,
                     'df_eq_g': 7,
                     'df_comp_th': -30,
                     'df_vol': 3.3,
                     'df_atten_lim': 100,
                     'w_df_no_speech': 0.36,
                     'w_df_logprob': -2.4,
                     'w_df_comp': 2.4,
                     'w_df_temp_max': 0.4,
                     'none_hp': 90,
                     'none_lp': 3200,
                     'none_nf': -32,
                     'none_target': -14,
                     'none_comp_th': -28,
                     'none_vol': 4.0,
                     'w_none_no_speech': 0.82,
                     'w_none_logprob': -1.0,
                     'w_none_comp': 1.6,
                     'w_none_temp_max': 0.0,
                     'w_beam_size': 6,
                     'w_patience': 1.2,
                     'w_length_penalty': 1.0,
                     'io_workers': 10,
                     'llm_threads': 6,
                     'ff_threads': 0,
                     'ff_ac': 1,
                     'ff_ar': 16000,
                     'ff_hp': 90,
                     'ff_lp': 3200,
                     'ff_nf': -32,
                     'ff_chunk': 30,
                     'ff_dynaudnorm_m': 10.0,
                     'ff_dynaudnorm_p': 0.95,
                     'ff_treble_boost': 0.0,
                     'continuous_threshold': 2.0,
                     'gap_pull_rate': 0.18,
                     'gap_push_rate': 0.82,
                     'single_subtitle_end': 0.2,
                     'split_length_threshold': 10,
                     'sub_min_duration': 0.3,
                     'sub_max_cps': 12,
                     'sub_dedup_window': 0.5,
                     'sub_gap_break_sec': 1.5,
                     'prefetch_ahead': 3,
                     'stt_parallel_level': 3,
                     'video_ui_interval_ms': 33,
                     'vad_threshold_disabled': False,
                     'vad_min_speech_disabled': False,
                     'vad_min_silence_disabled': False,
                     'vad_speech_pad_disabled': False,
                     'vad_window_size_disabled': False,
                     'df_hp_disabled': False,
                     'df_eq_g_disabled': False,
                     'df_comp_th_disabled': False,
                     'df_vol_disabled': False,
                     'df_atten_lim_disabled': False,
                     'w_df_no_speech_disabled': False,
                     'w_df_logprob_disabled': False,
                     'w_df_comp_disabled': False,
                     'w_df_temp_max_disabled': False,
                     'none_hp_disabled': False,
                     'none_lp_disabled': False,
                     'none_nf_disabled': False,
                     'none_target_disabled': False,
                     'none_comp_th_disabled': False,
                     'none_vol_disabled': False,
                     'w_none_no_speech_disabled': False,
                     'w_none_logprob_disabled': False,
                     'w_none_comp_disabled': False,
                     'w_none_temp_max_disabled': False,
                     'w_beam_size_disabled': False,
                     'w_patience_disabled': False,
                     'w_length_penalty_disabled': False,
                     'io_workers_disabled': False,
                     'llm_threads_disabled': False,
                     'ff_threads_disabled': False,
                     'ff_ac_disabled': False,
                     'ff_ar_disabled': False,
                     'ff_hp_disabled': False,
                     'ff_lp_disabled': False,
                     'ff_nf_disabled': False,
                     'ff_chunk_disabled': False,
                     'ff_dynaudnorm_m_disabled': False,
                     'ff_dynaudnorm_p_disabled': False,
                     'ff_treble_boost_disabled': False,
                     'continuous_threshold_disabled': False,
                     'gap_pull_rate_disabled': False,
                     'gap_push_rate_disabled': False,
                     'single_subtitle_end_disabled': False,
                     'split_length_threshold_disabled': False,
                     'sub_min_duration_disabled': False,
                     'sub_max_cps_disabled': False,
                     'sub_dedup_window_disabled': False,
                     'sub_gap_break_sec_disabled': False,
                     'prefetch_ahead_disabled': False,
                     'stt_parallel_level_disabled': False,
                     'video_ui_interval_ms_disabled': False}},
 '스마트폰': {'description': '스마트폰 내장 마이크',
          'settings': {'vad_threshold': 0.44,
                       'vad_min_speech': 0.22,
                       'vad_min_silence': 1.4,
                       'vad_speech_pad': 0.12,
                       'vad_window_size': 512,
                       'df_hp': 130,
                       'df_eq_g': 10,
                       'df_comp_th': -27,
                       'df_vol': 4.4,
                       'df_atten_lim': 100,
                       'w_df_no_speech': 0.54,
                       'w_df_logprob': -2.55,
                       'w_df_comp': 2.4,
                       'w_df_temp_max': 0.4,
                       'none_hp': 90,
                       'none_lp': 3200,
                       'none_nf': -32,
                       'none_target': -14,
                       'none_comp_th': -28,
                       'none_vol': 4.0,
                       'w_none_no_speech': 0.82,
                       'w_none_logprob': -1.0,
                       'w_none_comp': 1.6,
                       'w_none_temp_max': 0.0,
                       'w_beam_size': 6,
                       'w_patience': 1.2,
                       'w_length_penalty': 1.0,
                       'io_workers': 10,
                       'llm_threads': 6,
                       'ff_threads': 0,
                       'ff_ac': 1,
                       'ff_ar': 16000,
                       'ff_hp': 105,
                       'ff_lp': 5000,
                       'ff_nf': -28,
                       'ff_chunk': 25,
                       'ff_dynaudnorm_m': 13.0,
                       'ff_dynaudnorm_p': 0.96,
                       'ff_treble_boost': 2.0,
                       'continuous_threshold': 2.0,
                       'gap_pull_rate': 0.18,
                       'gap_push_rate': 0.82,
                       'single_subtitle_end': 0.2,
                       'split_length_threshold': 10,
                       'sub_min_duration': 0.3,
                       'sub_max_cps': 12,
                       'sub_dedup_window': 0.5,
                       'sub_gap_break_sec': 1.5,
                       'prefetch_ahead': 3,
                       'stt_parallel_level': 3,
                       'video_ui_interval_ms': 33,
                       'vad_threshold_disabled': False,
                       'vad_min_speech_disabled': False,
                       'vad_min_silence_disabled': False,
                       'vad_speech_pad_disabled': False,
                       'vad_window_size_disabled': False,
                       'df_hp_disabled': False,
                       'df_eq_g_disabled': False,
                       'df_comp_th_disabled': False,
                       'df_vol_disabled': False,
                       'df_atten_lim_disabled': False,
                       'w_df_no_speech_disabled': False,
                       'w_df_logprob_disabled': False,
                       'w_df_comp_disabled': False,
                       'w_df_temp_max_disabled': False,
                       'none_hp_disabled': False,
                       'none_lp_disabled': False,
                       'none_nf_disabled': False,
                       'none_target_disabled': False,
                       'none_comp_th_disabled': False,
                       'none_vol_disabled': False,
                       'w_none_no_speech_disabled': False,
                       'w_none_logprob_disabled': False,
                       'w_none_comp_disabled': False,
                       'w_none_temp_max_disabled': False,
                       'w_beam_size_disabled': False,
                       'w_patience_disabled': False,
                       'w_length_penalty_disabled': False,
                       'io_workers_disabled': False,
                       'llm_threads_disabled': False,
                       'ff_threads_disabled': False,
                       'ff_ac_disabled': False,
                       'ff_ar_disabled': False,
                       'ff_hp_disabled': False,
                       'ff_lp_disabled': False,
                       'ff_nf_disabled': False,
                       'ff_chunk_disabled': False,
                       'ff_dynaudnorm_m_disabled': False,
                       'ff_dynaudnorm_p_disabled': False,
                       'ff_treble_boost_disabled': False,
                       'continuous_threshold_disabled': False,
                       'gap_pull_rate_disabled': False,
                       'gap_push_rate_disabled': False,
                       'single_subtitle_end_disabled': False,
                       'split_length_threshold_disabled': False,
                       'sub_min_duration_disabled': False,
                       'sub_max_cps_disabled': False,
                       'sub_dedup_window_disabled': False,
                       'sub_gap_break_sec_disabled': False,
                       'prefetch_ahead_disabled': False,
                       'stt_parallel_level_disabled': False,
                       'video_ui_interval_ms_disabled': False,
                       'df_lp': 5400,
                       'df_nf': -28}},
 '차량': {'description': '차량 실내/노면 소음',
        'settings': {'vad_threshold': 0.56,
                     'vad_min_speech': 0.22,
                     'vad_min_silence': 1.3,
                     'vad_speech_pad': 0.12,
                     'vad_window_size': 512,
                     'df_hp': 190,
                     'df_eq_g': 11,
                     'df_comp_th': -23,
                     'df_vol': 4.7,
                     'df_atten_lim': 100,
                     'w_df_no_speech': 0.64,
                     'w_df_logprob': -2.55,
                     'w_df_comp': 2.45,
                     'w_df_temp_max': 0.3,
                     'none_hp': 90,
                     'none_lp': 3200,
                     'none_nf': -32,
                     'none_target': -14,
                     'none_comp_th': -28,
                     'none_vol': 4.0,
                     'w_none_no_speech': 0.82,
                     'w_none_logprob': -1.0,
                     'w_none_comp': 1.6,
                     'w_none_temp_max': 0.0,
                     'w_beam_size': 6,
                     'w_patience': 1.2,
                     'w_length_penalty': 1.0,
                     'io_workers': 10,
                     'llm_threads': 6,
                     'ff_threads': 0,
                     'ff_ac': 1,
                     'ff_ar': 16000,
                     'ff_hp': 150,
                     'ff_lp': 3800,
                     'ff_nf': -24,
                     'ff_chunk': 25,
                     'ff_dynaudnorm_m': 15.0,
                     'ff_dynaudnorm_p': 0.97,
                     'ff_treble_boost': 2.5,
                     'continuous_threshold': 2.0,
                     'gap_pull_rate': 0.18,
                     'gap_push_rate': 0.82,
                     'single_subtitle_end': 0.2,
                     'split_length_threshold': 10,
                     'sub_min_duration': 0.3,
                     'sub_max_cps': 12,
                     'sub_dedup_window': 0.5,
                     'sub_gap_break_sec': 1.5,
                     'prefetch_ahead': 3,
                     'stt_parallel_level': 3,
                     'video_ui_interval_ms': 33,
                     'vad_threshold_disabled': False,
                     'vad_min_speech_disabled': False,
                     'vad_min_silence_disabled': False,
                     'vad_speech_pad_disabled': False,
                     'vad_window_size_disabled': False,
                     'df_hp_disabled': False,
                     'df_eq_g_disabled': False,
                     'df_comp_th_disabled': False,
                     'df_vol_disabled': False,
                     'df_atten_lim_disabled': False,
                     'w_df_no_speech_disabled': False,
                     'w_df_logprob_disabled': False,
                     'w_df_comp_disabled': False,
                     'w_df_temp_max_disabled': False,
                     'none_hp_disabled': False,
                     'none_lp_disabled': False,
                     'none_nf_disabled': False,
                     'none_target_disabled': False,
                     'none_comp_th_disabled': False,
                     'none_vol_disabled': False,
                     'w_none_no_speech_disabled': False,
                     'w_none_logprob_disabled': False,
                     'w_none_comp_disabled': False,
                     'w_none_temp_max_disabled': False,
                     'w_beam_size_disabled': False,
                     'w_patience_disabled': False,
                     'w_length_penalty_disabled': False,
                     'io_workers_disabled': False,
                     'llm_threads_disabled': False,
                     'ff_threads_disabled': False,
                     'ff_ac_disabled': False,
                     'ff_ar_disabled': False,
                     'ff_hp_disabled': False,
                     'ff_lp_disabled': False,
                     'ff_nf_disabled': False,
                     'ff_chunk_disabled': False,
                     'ff_dynaudnorm_m_disabled': False,
                     'ff_dynaudnorm_p_disabled': False,
                     'ff_treble_boost_disabled': False,
                     'continuous_threshold_disabled': False,
                     'gap_pull_rate_disabled': False,
                     'gap_push_rate_disabled': False,
                     'single_subtitle_end_disabled': False,
                     'split_length_threshold_disabled': False,
                     'sub_min_duration_disabled': False,
                     'sub_max_cps_disabled': False,
                     'sub_dedup_window_disabled': False,
                     'sub_gap_break_sec_disabled': False,
                     'prefetch_ahead_disabled': False,
                     'stt_parallel_level_disabled': False,
                     'video_ui_interval_ms_disabled': False,
                     'df_lp': 4200,
                     'df_nf': -24}}}
