from __future__ import annotations

import os
from copy import deepcopy
from typing import Any

from core.autopilot_policy import apply_autopilot_runtime_policy, autopilot_runtime_defaults
from core.json_file import read_json_file
from core.mode_manager import apply_mode_scope_quality, selected_mode_from_settings
from core.mode_policy import apply_mode_runtime_settings
from core.runtime import config
from core.speaker_profile_settings import materialize_automatic_speaker_settings


USER_SETTINGS_SCHEMA = "ai_subtitle_studio.user_settings.v2"
PERSISTED_SECRET_SETTING_KEYS = frozenset(
    {
        "google_api_key",
        "openai_api_key",
        "huggingface_token",
        "huggingface_api_key",
        "hf_token",
    }
)


UI_ENGINE_DEFAULTS: dict[str, Any] = {
    "settings_simplified_ui_enabled": True,
    "simple_operation_mode": "auto",
    "selected_audio_ai": "deepfilter",
    "selected_vad": "silero",
    "selected_whisper_model": getattr(config, "WHISPER_MODEL", "large-v3"),
    "selected_model": getattr(config, "OLLAMA_MODEL", "exaone3.5:7.8b"),
    "selected_llm_provider": "ollama",
    "ollama_python_client_enabled": True,
    "auto_start_mode": "balanced",
    "stt_quality_preset": "balanced",
    "editor_auto_save_interval_sec": 300,
    "audio_preset": "",
    "vad_threshold": 0.5,
    "vad_min_speech": 0.25,
    "vad_min_silence": 2.0,
    "vad_speech_pad": 0.1,
    "vad_window_size": 512,
    "df_atten_lim": 100,
    "none_hp": 80,
    "none_lp": 3000,
    "none_nf": -25,
    "none_target": -14,
    "ff_threads": 0,
    "ffmpeg_filter_threads": 8,
    "ff_ac": 1,
    "ff_ar": 16000,
    "ff_hp": 200,
    "ff_lp": 3000,
    "ff_nf": -25,
    "ff_chunk": 30,
    "wav_pcm_fast_chunk_extract": True,
    "direct_ffmpeg_chunk_extract": True,
    "direct_ffmpeg_chunk_min_sec": 1.0,
    "direct_ffmpeg_chunk_batch_extract": True,
    "direct_ffmpeg_chunk_batch_size": 8,
    "direct_ffmpeg_chunk_batch_max_span_sec": 240.0,
    "clearvoice_native_ffmpeg_enabled": True,
    "ff_dynaudnorm_m": 10.0,
    "ff_dynaudnorm_p": 0.95,
    "ff_treble_boost": 0.0,
    "w_beam_size": 5,
    "w_patience": 1.0,
    "w_length_penalty": 1.0,
    "continuous_threshold": 2.0,
    "subtitle_lora_micro_merge_enabled": True,
    "subtitle_lora_micro_merge_min_duration": 0.8,
    "subtitle_lora_micro_merge_gap_sec": 1.8,
    "subtitle_lora_micro_merge_word_gap_sec": 1.2,
    "subtitle_lora_micro_merge_continuous_sec": 3.0,
    "gap_push_rate": 0.7,
    "gap_pull_rate": 0.2,
    "single_subtitle_end": 0.2,
    "sub_max_duration": 6.0,
    "subtitle_lora_split_floor_enabled": True,
    "subtitle_lora_split_floor_chars": 20,
    "subtitle_common_split_guard_enabled": True,
    "subtitle_common_split_target_chars": 20,
    "subtitle_common_split_hard_max_chars": 32,
    "subtitle_common_split_hard_max_duration_sec": 5.5,
    "chunk_time_limit": 180,
    "subtitle_bundle_autopilot_enabled": True,
    "subtitle_bundle_lora_enabled": True,
    "subtitle_bundle_lora_blend": 0.35,
    "subtitle_bundle_target_sec": 240,
    "subtitle_bundle_min_sec": 120,
    "subtitle_bundle_max_sec": 420,
    "subtitle_bundle_use_confirmed_cuts": True,
    "subtitle_bundle_use_provisional_cuts": True,
    "subtitle_bundle_confirmed_cut_min_sec": 45,
    "subtitle_bundle_provisional_cut_min_sec": 120,
    "subtitle_bundle_boundary_snap_window_sec": 1.0,
    "background_prefetch_enabled": True,
    "background_prefetch_before_sec": 18.0,
    "background_prefetch_after_sec": 72.0,
    "background_prefetch_segment_limit": 10,
    "background_prefetch_lora_enabled": False,
    "background_prefetch_lora_limit": 2,
    "background_prefetch_lora_retrieval_limit": 2,
    "background_prefetch_candidates_enabled": False,
    "background_prefetch_candidate_limit": 4,
    "background_prefetch_bucket_sec": 6.0,
    "background_prefetch_min_interval_sec": 0.75,
    "runtime_npu_acceleration_enabled": True,
    "stt_npu_prefer_enabled": True,
    "live_stt_npu_prefer_enabled": True,
    "stt_whisperkit_concurrent_workers": 4,
    "stt_whisperkit_recheck_concurrent_workers": 8,
    "stt_whisperkit_recheck_concurrent_max_workers": 10,
    "stt_whisperkit_word_timestamp_concurrent_workers": 8,
    "stt_whisperkit_concurrent_max_workers": 10,
    "stt_whisperkit_native_allocator_can_raise_workers": True,
    "stt_whisperkit_gpu_saturation_max_workers": 10,
    "stt_whisperkit_precision_aggressive_gpu_enabled": True,
    "stt_whisperkit_stream_results_enabled": True,
    "stt_whisperkit_native_compute_profile_enabled": True,
    "stt_whisperkit_compute_profile": "auto",
    "stt_worker_response_timeout_sec": 150.0,
    "stt_worker_word_timestamp_response_timeout_sec": 90.0,
    "stt_word_timestamp_worker_response_timeout_sec": 45.0,
    "stt_word_timestamp_worker_straggler_timeout_sec": 12.0,
    "stt_word_timestamp_worker_straggler_max_missing_chunks": 1,
    "stt_word_timestamp_worker_straggler_min_received_ratio": 0.90,
    "stt_word_timestamp_straggler_skip_enabled": True,
    "stt_recheck_worker_straggler_timeout_sec": 18.0,
    "stt_recheck_worker_straggler_max_missing_chunks": 4,
    "stt_recheck_worker_straggler_min_received_ratio": 0.60,
    "stt_recheck_straggler_skip_enabled": True,
    "audio_torch_gpu_enabled": True,
    "editor_rendering_gpu_enabled": True,
    "editor_rendering_gpu_scope": "all",
    "editor_rendering_opengl_widgets_enabled": True,
    "editor_rendering_scenegraph_enabled": True,
    "editor_rendering_force_qt_opengl": False,
    "editor_rendering_qt_backend": "auto",
    "runtime_hardware_acceleration_enabled": True,
    "apple_m_pipeline_parallel_enabled": True,
    "apple_m_chip_aware_scheduler_enabled": True,
    "apple_m_pipeline_respect_manual_worker_settings": False,
    "runtime_backend_autotune_enabled": True,
    "stt_backend_policy": "native",
    "vad_backend_policy": "auto",
    "native_swift_vad_segments_enabled": True,
    "stt_apple_speech_challenger_enabled": False,
    "stt_apple_speech_vad_coupled_enabled": False,
    "stt_apple_speech_locale": "ko-KR",
    "stt_apple_speech_benchmark_only": True,
    "cut_boundary_backend_policy": "native",
    "audio_extract_backend_policy": "native",
    "llm_backend_policy": "auto",
    "editor_render_backend_policy": "native",
    "whisperkit_native_auto_enabled": True,
    "ffmpeg_videotoolbox_decode_enabled": True,
    "macos_native_fast_audio_flatten_enabled": True,
    "macos_native_fast_audio_flatten_hp": 150,
    "macos_native_fast_audio_flatten_lp": 4600,
    "macos_native_fast_audio_flatten_comp_th": -24,
    "macos_native_fast_audio_flatten_volume": 3.2,
    "macos_native_fast_audio_flatten_limiter": 0.93,
    "macos_native_app_store_target_enabled": True,
    "macos_native_require_xcode_tools": True,
    "runtime_performance_profile": "max",
    "runtime_native_threads_auto_enabled": True,
    "runtime_native_threads": 8,
    "runtime_native_json_enabled": True,
    "runtime_native_text_similarity_enabled": True,
    "runtime_native_cut_boundary_enabled": True,
    "mac_native_acceleration_enabled": True,
    "native_cpp_llm_macro_groups_enabled": True,
    "native_swift_quality_scoring_enabled": True,
    "native_swift_quality_scoring_min_segments": 64,
    "native_swift_common_split_enabled": True,
    "native_swift_common_split_min_items": 1000,
    # BENCH LOCK 2026-05-09: Python remains the production policy path. Swift
    # worker was slower for LLM/Deep/LoRA and changed LoRA top-5 ranking.
    "native_swift_llm_candidate_policy_enabled": False,
    "native_swift_deep_policy_enabled": False,
    "native_swift_lora_scoring_enabled": False,
    "native_swift_lora_scoring_min_docs": 32,
    "runtime_scheduler_ramp_up_enabled": True,
    "runtime_scheduler_ramp_initial_sec": 45.0,
    "runtime_scheduler_ramp_step_sec": 60.0,
    "runtime_scheduler_reserve_cores": 0,
    "runtime_monitor_terminal_log_enabled": False,
    "runtime_memory_monitor_interval_ms": 15000,
    "runtime_memory_disk_cache_budget_gb": 12.0,
    "runtime_memory_tracemalloc_enabled": False,
    "runtime_memory_tracemalloc_frames": 8,
    "macos_native_memory_snapshot_enabled": True,
    "macos_allocator_pressure_relief_enabled": True,
    "macos_allocator_pressure_relief_warning_mb": 64,
    "macos_allocator_pressure_relief_critical_mb": 256,
    "subtitle_generation_memory_guard_enabled": True,
    "subtitle_generation_memory_checkpoint_interval_ms": 3000,
    "subtitle_generation_gpu_trim_cooldown_sec": 8.0,
    "runtime_memory_warning_ratio": 0.20,
    "runtime_memory_critical_ratio": 0.12,
    "runtime_memory_warning_trim_cooldown_sec": 12.0,
    "runtime_memory_critical_trim_cooldown_sec": 6.0,
    "runtime_memory_warning_disk_trim_ratio": 0.72,
    "runtime_memory_critical_disk_trim_ratio": 0.45,
    "macos_memory_warning_reserve_gb": 3.0,
    "macos_memory_critical_reserve_gb": 1.5,
    "macos_memory_compressed_warning_ratio": 0.22,
    "macos_memory_compressed_critical_ratio": 0.30,
    "macos_memory_trim_runtime_caches_enabled": True,
    "macos_memory_cache_prune_enabled": True,
    "project_external_srt_storage_enabled": True,
    "subtitle_cut_boundary_guard_enabled": True,
    "subtitle_cut_boundary_allow_high_confidence_crossing": False,
    "subtitle_cut_boundary_high_confidence_score": 96.0,
    "prefetch_ahead": 3,
    "io_workers": 6,
    "segment_lora_min_score": 28.0,
    "segment_lora_retrieval_limit": 8,
    "segment_lora_retrieval_per_kind": 2,
    "lora_retrieval_skip_large_runtime_index": True,
    "lora_retrieval_runtime_max_index_mb": 128.0,
    "lora_gpu_acceleration_enabled": True,
    "lora_gpu_prefer_mps": True,
    "lora_gpu_retrieval_scoring_enabled": True,
    "lora_gpu_retrieval_min_postings": 256,
    "lora_gpu_force_small_batches": False,
    "lora_pattern_index_enabled": True,
    "lora_pattern_first_enabled": True,
    "lora_pattern_autobuild_enabled": True,
    "lora_pattern_query_compact_enabled": True,
    "lora_pattern_skip_text_retrieval_score": 78.0,
    "lora_store_full_text_enabled": False,
    "voice_lora_bridge_enabled": False,
    "voice_lora_audio_extraction_enabled": False,
    "stt1_adapter_audio_extraction_enabled": False,
    "deep_policy_pattern_only_enabled": True,
    "deep_subtitle_policy_enabled": True,
    "deep_segment_setting_policy_enabled": True,
    "deep_subtitle_reranker_enabled": True,
    "deep_subtitle_reranker_min_margin": 0.03,
    "deep_stt_candidate_selector_enabled": True,
    "deep_stt_candidate_min_score": 0.56,
    "deep_stt_candidate_min_margin": 0.18,
    "deep_timing_adjustment_enabled": True,
    "deep_timing_max_shift_sec": 0.12,
    "subtitle_timing_fusion_enabled": True,
    "subtitle_timing_fusion_max_shift_sec": 0.18,
    "subtitle_timing_fusion_word_weight": 0.72,
    "subtitle_timing_fusion_vad_weight": 0.46,
    "subtitle_timing_fusion_lora_duration_weight": 0.22,
    "subtitle_timing_fusion_boundary_snap_window_sec": 0.12,
    "deep_sequence_smoothing_enabled": True,
    "deep_sequence_max_shift_sec": 0.18,
    "deep_sequence_bridge_gap_sec": 0.3,
    "deep_segment_setting_exploration_rate": 0.04,
    "deep_policy_event_logging_enabled": False,
    "deep_policy_event_max_rows_per_run": 128,
    "deep_policy_hard_case_margin": 0.08,
    "deep_hard_case_mining_enabled": True,
    "hardcase_training_queue_enabled": True,
    "hardcase_training_queue_max_items_per_run": 48,
    "stt_lattice_selector_enabled": True,
    "stt_lattice_min_confidence": 0.62,
    "stt_lattice_replace_margin": 0.14,
    "stt_lattice_min_match_score": 0.42,
    "stt_selection_min_raw_candidate_similarity": 0.72,
    "stt_selection_score_fallback_enabled": True,
    "stt_selection_score_fallback_min_score": 84.0,
    "stt_selection_score_fallback_min_margin": 12.0,
    "stt_lattice_require_word_timestamps": True,
    "stt_lattice_persist_enabled": True,
    "stt_lattice_artifact_candidate_limit": 16,
    "stt_lattice_artifact_word_limit": 64,
    "stt_persistent_runtime_reuse_enabled": True,
    # BENCH LOCK 2026-05-09: SRT-referenced 1-minute benchmark keeps STT1 on
    # WhisperKit quality; MLX turbo is STT2/recheck. Do not flip without WER/CER.
    "stt_primary_fast_native_enabled": False,
    "stt_primary_fast_native_model": getattr(config, "WHISPERKIT_QUALITY_MODEL", "whisperkit-persistent:large-v3-v20240930_626MB"),
    "editor_live_stt_preview_follow_video_enabled": True,
    "editor_live_stt_preview_follow_interval_sec": 0.45,
    "stt_recheck_native_fast_audio_filter_enabled": True,
    "stt_low_score_recheck_enabled": True,
    "stt_low_score_recheck_threshold": 78,
    "stt_low_score_recheck_padding_sec": 0.45,
    "stt_low_score_recheck_max_segments": 24,
    "stt_low_score_recheck_max_audio_sec": 110.0,
    "stt_low_score_recheck_min_improvement": 2.0,
    "stt_word_timestamps_mode": "selective",
    "stt_word_timestamps_default_enabled": False,
    "stt_word_timestamps_precision_enabled": True,
    "stt_word_timestamps_precision_threshold": 72.0,
    "stt_word_timestamps_precision_max_segments": 24,
    "stt_word_timestamps_precision_max_audio_sec": 90.0,
    "stt_word_timestamps_precision_keep_text": True,
    "stt_word_timestamps_precision_min_similarity": 0.18,
    "stt_word_timestamps_precision_max_timing_shift_sec": 0.55,
    "stt_word_timestamps_precision_min_duration_ratio": 0.45,
    "stt_word_timestamps_precision_max_duration_ratio": 1.8,
    "stt_ensemble_selective_enabled": False,
    "stt_ensemble_parallel_enabled": False,
    "stt_missing_voice_min_duration_sec": 0.55,
    "llm_confidence_gate_enabled": True,
    "llm_confidence_gate_min_lora_score": 82.0,
    "llm_confidence_gate_max_compact_ratio": 1.45,
    "llm_confidence_gate_strong_signal_score": 88.0,
    "llm_confidence_gate_strong_max_compact_ratio": 1.85,
    "llm_confidence_gate_strong_max_duration_ratio": 1.65,
    "subtitle_llm_macro_chunk_enabled": True,
    "subtitle_llm_macro_chunk_min_rows": 10,
    "subtitle_llm_macro_chunk_max_rows": 15,
    "subtitle_llm_macro_chunk_use_cut_boundaries": True,
    "subtitle_llm_prev_next_context_enabled": True,
    "subtitle_llm_context_candidate_limit": 5,
    "subtitle_llm_context_min_current_similarity": 0.86,
    "subtitle_llm_context_neighbor_reject_margin": 0.06,
    "subtitle_llm_context_boundary_refine_enabled": False,
    "subtitle_llm_context_word_correction_enabled": True,
    "subtitle_llm_context_max_pairs": 8,
    "subtitle_llm_context_require_risk_signal": True,
    "subtitle_llm_context_max_pair_gap_sec": 0.85,
    "subtitle_llm_context_min_pair_chars": 6,
    "subtitle_llm_context_max_pair_chars": 58,
    "subtitle_llm_context_allow_merge": True,
    "subtitle_llm_context_merge_max_chars": 32,
    "subtitle_llm_context_merge_micro_max_chars": 4,
    "subtitle_llm_context_merge_micro_max_duration_sec": 0.55,
    "subtitle_llm_context_max_word_corrections": 2,
    "subtitle_llm_context_timeout_sec": 45.0,
    "subtitle_llm_context_num_predict": 180,
    "subtitle_llm_text_only_timing_lock_enabled": True,
    "subtitle_final_stt_slot_order_guard_enabled": True,
    "stt_window_drift_report_enabled": True,
    "vad_voice_start_priority_max_stt_lead_sec": 0.12,
    "subtitle_native_prepass_workers": 0,
    "subtitle_native_prepass_workers_resource_max": 0,
    "codex_subtitle_native_fast_path_enabled": True,
    "codex_subtitle_native_fast_path_min_segments": 80,
    "codex_subtitle_native_fast_path_long_text_llm_ratio": 2.8,
    "llm_minimize_enabled": True,
    "llm_minimize_min_gate_confidence": 0.74,
    "llm_minimize_required_signal_score": 82.0,
    "llm_candidate_policy_enabled": True,
    "llm_candidate_policy_max_candidates": 4,
    "llm_candidate_policy_allow_minimal_edit": True,
    "llm_candidate_policy_max_edit_ratio": 0.04,
    "linebreak_lora_policy_enabled": True,
    "linebreak_lora_policy_max_patterns": 3,
    "subtitle_target_line_count": 0,
    "subtitle_target_line_count_auto_enabled": True,
    "llm_verifier_enabled": True,
    "llm_verifier_min_similarity": 0.86,
    "llm_verifier_max_length_delta_ratio": 0.16,
    "llm_verifier_short_text_compact_len": 10,
    "llm_verifier_long_text_compact_len": 28,
    "llm_verifier_short_text_max_length_delta_ratio": 0.12,
    "llm_verifier_long_text_max_length_delta_ratio": 0.22,
    "llm_verifier_short_duration_sec": 1.2,
    "llm_verifier_long_duration_sec": 3.6,
    "llm_verifier_short_duration_delta_adjust": -0.01,
    "llm_verifier_long_duration_delta_adjust": 0.02,
    "llm_verifier_max_chunks": 4,
    "llm_verifier_preserve_numbers": True,
    "llm_verifier_preserve_proper_nouns": True,
    "llm_verifier_preserve_interjections": True,
    "llm_verifier_block_added_content_tokens": True,
    "accuracy_decision_graph_enabled": True,
    "accuracy_graph_persist_enabled": False,
    "subtitle_accuracy_metrics_enabled": True,
    "subtitle_output_selector_enabled": True,
    "subtitle_context_consistency_enabled": True,
    "subtitle_context_repeat_window_sec": 4.0,
    "subtitle_context_near_duplicate_ratio": 0.94,
    "subtitle_context_cps_jump_ratio": 2.6,
    "subtitle_context_score_penalty_weight": 0.32,
    "subtitle_context_repair_enabled": True,
    "subtitle_context_repair_drop_repeats": True,
    "subtitle_context_repair_drop_empty_enabled": True,
    "subtitle_context_repair_drop_hallucinations_enabled": True,
    "subtitle_context_repair_overlap_pad_sec": 0.02,
    "subtitle_context_repair_min_duration_sec": 0.2,
    "subtitle_context_repair_cps_jumps_enabled": True,
    "subtitle_context_repair_cps_max_extend_sec": 0.4,
    "subtitle_lora_style_consistency_enabled": True,
    "subtitle_lora_style_min_profile_score": 28.0,
    "subtitle_lora_style_max_length_drift_ratio": 1.25,
    "subtitle_lora_style_max_line_drift": 1,
    "subtitle_lora_style_max_cps_ratio": 2.0,
    "subtitle_lora_style_score_penalty_weight": 0.22,
    "editor_truth_capture_enabled": True,
    "editor_truth_capture_min_chars": 2,
    "editor_truth_capture_max_chars": 240,
    "editor_truth_runtime_apply_enabled": True,
    "editor_truth_runtime_min_similarity": 0.94,
    "editor_truth_runtime_pattern_limit": 80,
    "user_edit_metrics_enabled": True,
    "user_edit_metrics_deep_event_enabled": True,
    "user_edit_metrics_hard_case_score": 24.0,
    "user_edit_metrics_text_ratio_hard": 0.18,
    "user_edit_metrics_timing_shift_hard_sec": 0.3,
    "runtime_quality_self_review_enabled": False,
    "deep_quality_event_logging_enabled": False,
    "deep_quality_event_all_segments": False,
    "deep_quality_event_min_score": 85.0,
    "subtitle_decision_explanation_logging_enabled": False,
    "uncertainty_first_enabled": True,
    "uncertainty_first_process_order": "easy_first",
    "uncertainty_first_easy_score": 18.0,
    "uncertainty_first_precision_score": 52.0,
    "uncertainty_first_easy_signal_score": 82.0,
    "uncertainty_first_low_stt_score": 58.0,
    "uncertainty_first_low_lora_score": 58.0,
    "uncertainty_first_long_text_ratio": 1.45,
    "deep_runtime_adaptation_enabled": True,
    "deep_runtime_adaptation_min_events": 8,
    "deep_runtime_adaptation_lookback_events": 256,
    "deep_runtime_adaptation_rate": 1.0,
    "lora_user_settings_autopilot_enabled": True,
    "lora_user_settings_auto_apply_min_score": 88.0,
    "lora_user_settings_auto_apply_categorical_min_score": 92.0,
    "lora_user_settings_auto_apply_blend": 0.35,
    "lora_user_settings_exploration_rate": 0.12,
    "lora_user_settings_exploration_min_truth_rows": 12,
    "lora_user_settings_exploration_max_bundles": 1,
    **autopilot_runtime_defaults(),
}


CUT_BOUNDARY_DEFAULTS: dict[str, Any] = {
    "cut_boundary_detection_enabled": True,
    "cut_boundary_enabled": True,
    "cut_boundary_level": "medium",
    "scan_cut_enabled": True,
    "scan_cut_auto_enabled": True,
    "playhead_auto_cut_magnet_enabled": True,
    "playhead_auto_cut_magnet_strict_verify_enabled": True,
    "playhead_auto_cut_magnet_strict_multiplier": 1.22,
    "playhead_auto_cut_magnet_verify_window_sec": 0.42,
    "scan_cut_boundary_level": "medium",
    "scan_cut_level": "medium",
    "scan_cut_auto_sample_step_sec": 2.0,
    "scan_cut_auto_min_gap_sec": 8.0,
    "scan_cut_auto_threshold": 24.0,
    "scan_cut_threshold": 24.0,
    "scan_cut_audio_gain_enabled": True,
    "scan_cut_use_preview_proxy_enabled": True,
    "scan_cut_cv2_video_backend": "avfoundation",
    "scan_cut_provisional_sample_step_sec": 2.0,
    "scan_cut_long4k_provisional_sample_step_sec": 4.0,
    "scan_cut_no_proxy_pioneer_max_samples": 180,
    "scan_cut_no_proxy_min_sample_step_sec": 8.0,
    "scan_cut_provisional_compare_max_width": 640,
    "scan_cut_provisional_compare_max_height": 360,
    "scan_cut_pioneer_packet_scout_enabled": True,
    "scan_cut_pioneer_packet_scout_timeout_sec": 60.0,
    "scan_cut_pioneer_packet_scout_raw_candidates": 180,
    "scan_cut_pioneer_packet_bucket_sec": 0.25,
    "scan_cut_pioneer_packet_min_gap_sec": 0.20,
    "scan_cut_pioneer_packet_delta_threshold": 1.4,
    "scan_cut_pioneer_packet_mad_multiplier": 3.0,
    "scan_cut_pioneer_pipe_enabled": False,
    "scan_cut_pioneer_pipe_hwaccel_enabled": True,
    "scan_cut_pioneer_pipe_fps": 1.0,
    "scan_cut_pioneer_pipe_width": 320,
    "scan_cut_pioneer_pipe_height": 180,
    "scan_cut_pioneer_pipe_dense_flow_enabled": True,
    "scan_cut_pioneer_pipe_flow_width": 160,
    "scan_cut_pioneer_pipe_pixel_threshold": 15.0,
    "scan_cut_pioneer_pipe_pixel_strong_threshold": 28.0,
    "scan_cut_pioneer_pipe_flow_residual_threshold": 10.0,
    "scan_cut_pioneer_pipe_timeout_sec": 120.0,
    "scan_cut_pioneer_pipe_max_candidates": 360,
    "scan_cut_pioneer_min_gap_sec": 0.45,
    "scan_cut_pioneer_dense_flow_confirm_enabled": True,
    "scan_cut_pioneer_strict_multiplier": 0.72,
    "scan_cut_pioneer_gpu_refine_enabled": True,
    "scan_cut_pioneer_sequential_decode_enabled": False,
    "scan_cut_pioneer_candidate_fusion_enabled": True,
    "scan_cut_pioneer_fusion_window_sec": 0.35,
    "scan_cut_pioneer_fusion_max_candidates": 360,
    "scan_cut_follower_mps_enabled": False,
    "scan_cut_follower_dense_flow_enabled": True,
    "scan_cut_dense_flow_backend": "dis",
    "scan_cut_dense_flow_sequential_window_decode_enabled": True,
    "scan_cut_dense_flow_window_radius": 2,
    "scan_cut_dense_flow_width": 320,
    "scan_cut_dense_flow_diff_threshold": 18.0,
    "scan_cut_dense_flow_min_diff": 14.0,
    "scan_cut_dense_flow_strong_diff": 62.0,
    "scan_cut_dense_flow_min_motion_px": 0.8,
    "scan_cut_dense_flow_motion_residual_ratio": 0.88,
    "scan_cut_dense_flow_motion_coherence": 0.64,
    "scan_cut_dense_flow_min_coverage": 0.08,
    "scan_cut_dense_flow_motion_score_threshold": 0.56,
    "scan_cut_dense_flow_motion_votes_required": 2,
    "scan_cut_dense_flow_hard_cut_residual_ratio": 0.92,
    "scan_cut_dense_flow_fade_trend_protection_enabled": True,
    "scan_cut_dense_flow_fade_brightness_range": 18.0,
    "scan_cut_dense_flow_fade_motion_max_px": 1.8,
    "scan_cut_dense_flow_brightness_trend_epsilon": 1.5,
    # BENCH LOCK 2026-05-09 (Apple M5, X5_시승기_후반.MP4 4K HEVC):
    # 선발대 4 workers, 후발대 CPU 4-way outer split, OpenCV 1 thread/worker가
    # 실제 4K 영상에서 가장 빨랐습니다. 임의 변경 금지, 변경 시 벤치 재실행.
    "scan_cut_pioneer_workers": 4,
    "scan_cut_verify_workers": 4,
    "scan_cut_cv2_threads_per_worker": 1,
    "scan_cut_pioneer_cpu_max_workers": 4,
    "scan_cut_follower_cpu_max_workers": 4,
    "scan_cut_follower_outer_splits": 4,
    "scan_cut_pioneer_worker_overlap_steps": 1,
    "scan_cut_follower_stream_start_percent": 25,
    "scan_cut_follower_stream_batch_size": 16,
    "scan_cut_follower_stream_min_interval_sec": 0.75,
    "scan_cut_follower_visual_candidate_compact_gap_sec": 0.45,
    "scan_cut_follower_packet_candidate_compact_gap_sec": 0.20,
    "scan_cut_follower_scene_candidate_compact_gap_sec": 0.40,
    "scan_cut_high_cost_visual_skip_enabled": True,
    "scan_cut_high_cost_min_pixels": 8_000_000,
    "scan_cut_high_cost_min_bitrate": 80_000_000,
    "scan_cut_audio_gain_threshold_db": 10.0,
    "scan_cut_audio_gain_window_sec": None,
    "scan_cut_audio_gain_min_gap_sec": None,
    "scan_cut_audio_gain_sample_rate": 4000,
    "scan_cut_audio_gain_context_windows": 2,
    "scan_cut_audio_gain_timeout_sec": 45.0,
    "scan_cut_audio_gain_max_candidates": 240,
    "scan_cut_audio_spectral_flux_enabled": True,
    "scan_cut_audio_spectral_flux_window_sec": 0.50,
    "scan_cut_audio_spectral_flux_threshold_multiplier": 3.0,
    "scan_cut_ffmpeg_scene_prepass_enabled": False,
    "scan_cut_ffmpeg_scene_replace_opencv_enabled": False,
    "scan_cut_ffmpeg_scene_threshold": 0.35,
    "scan_cut_ffmpeg_scene_timeout_sec": 90.0,
    "scan_cut_ffmpeg_scene_max_candidates": 300,
    "scan_cut_progress_sample_stride": 4,
    "scan_cut_incremental_save_interval_sec": 0.75,
    "scan_cut_topicless_min_segment_sec": 120.0,
    "scan_cut_topicless_hard_min_segment_sec": 45.0,
    "scan_cut_topicless_audio_priority_min_segment_sec": 24.0,
    "scan_cut_topicless_audio_priority_window_sec": 12.0,
    "scan_cut_topicless_audio_snap_visual_window_sec": 8.0,
    "scan_cut_topicless_audio_hard_delta_db": 8.0,
    "scan_cut_topicless_visual_hard_score": 140.0,
    "roughcut_boundary_fusion_enabled": True,
    "cut_boundary_fusion_window_sec": 1.0,
    "cut_boundary_fusion_keep_threshold": 0.68,
    "cut_boundary_fusion_verify_threshold": 0.43,
    "roughcut_context_shift_boundary_threshold": 0.65,
    "roughcut_context_shift_min_gap_sec": 0.0,
    "deep_cut_boundary_model_enabled": True,
    "deep_cut_boundary_keep_threshold": 0.72,
    "deep_cut_boundary_verify_threshold": 0.46,
}


PATH_SETTING_DEFAULTS: dict[str, Any] = {
    "watch_folders": [],
    "fcpxml_output": os.path.join(config.BASE_DIR, "output", "FCPXML"),
    "last_folder": "",
    "nas_urls": {},
    "nas_path": "",
    "icloud_path": "",
    "recent_folders": [],
    "auto_detect_enabled": False,
    "nas_excluded_folders": [],
    "auto_start_mode": "balanced",
    "auto_start_enabled": True,
    "icloud_stt_quality_preset": "balanced",
    "nas_stt_quality_preset": "balanced",
    "multiclip_stt_quality_preset": "balanced",
    "icloud_auto_detect": False,
    "nas_auto_detect": False,
}


LLM_PROMPT_DEFAULTS: dict[str, Any] = {
    "user_prompt": "",
    "llm_prompt": "",
    "default_llm_prompt": getattr(config, "DEFAULT_LLM_PROMPT", ""),
    "editor_roughcut_draft_prompt": "",
    "roughcut_llm_prompt": "",
}

SPEED_SAFE_AUTO_PROFILE_VERSION = "03.21.auto_speed_safe.v1"
SPEED_SAFE_AUTO_DEFAULTS: dict[str, Any] = {
    "stt_ensemble_enabled": False,
    "stt_ensemble_llm_judge_enabled": False,
    "stt_ensemble_llm_judge_require_risk": True,
    "stt_ensemble_llm_judge_local_only": True,
    "stt_ensemble_llm_judge_low_score_threshold": 78.0,
    "stt_ensemble_llm_judge_min_score_delta": 10.0,
    "stt_ensemble_llm_judge_max_similarity": 0.94,
    "stt_selection_min_raw_candidate_similarity": 0.72,
    "stt_selection_score_fallback_enabled": True,
    "stt_selection_score_fallback_min_score": 84.0,
    "stt_selection_score_fallback_min_margin": 12.0,
    "stt_ensemble_selective_enabled": False,
    "stt_ensemble_parallel_enabled": False,
    "stt_word_timestamps_mode": "selective",
    "stt_word_timestamps_default_enabled": False,
    "stt_word_timestamps_precision_enabled": True,
    "stt_word_timestamps_precision_threshold": 72.0,
    "stt_word_timestamps_precision_max_segments": 16,
    "stt_word_timestamps_precision_max_audio_sec": 60.0,
    "stt_word_timestamps_precision_keep_text": True,
    "stt_word_timestamps_precision_min_similarity": 0.18,
    "stt_word_timestamps_precision_max_timing_shift_sec": 0.55,
    "stt_word_timestamps_precision_min_duration_ratio": 0.45,
    "stt_word_timestamps_precision_max_duration_ratio": 1.8,
    "stt_missing_voice_min_duration_sec": 0.55,
    "stt_low_score_recheck_enabled": True,
    "stt_low_score_recheck_threshold": 74,
    "stt_low_score_recheck_padding_sec": 0.50,
    "stt_low_score_recheck_max_segments": 18,
    "stt_low_score_recheck_max_audio_sec": 85.0,
    "stt_low_score_recheck_min_improvement": 1.5,
    "stt_persistent_runtime_reuse_enabled": True,
    "stt_primary_fast_native_enabled": False,
    "stt_primary_fast_native_model": getattr(config, "WHISPERKIT_QUALITY_MODEL", "whisperkit-persistent:large-v3-v20240930_626MB"),
    "editor_live_stt_preview_follow_video_enabled": True,
    "editor_live_stt_preview_follow_interval_sec": 0.45,
    "stt_recheck_native_fast_audio_filter_enabled": True,
    "whisper_chunk_overlap_sec": 1.5,
    "chunk_time_limit": 240,
    "subtitle_bundle_target_sec": 240,
    "subtitle_bundle_min_sec": 120,
    "subtitle_bundle_max_sec": 420,
    "scan_cut_level": "low",
    "cut_boundary_level": "low",
    "scan_cut_boundary_level": "low",
    "segment_lora_retrieval_limit": 8,
    "segment_lora_retrieval_per_kind": 2,
    "lora_retrieval_skip_large_runtime_index": True,
    "lora_retrieval_runtime_max_index_mb": 128.0,
    "lora_gpu_acceleration_enabled": True,
    "lora_gpu_prefer_mps": True,
    "lora_gpu_retrieval_scoring_enabled": True,
    "lora_gpu_retrieval_min_postings": 256,
    "lora_gpu_force_small_batches": False,
    "editor_truth_runtime_pattern_limit": 80,
    "stt_lattice_artifact_candidate_limit": 16,
    "stt_lattice_artifact_word_limit": 64,
    "llm_verifier_max_chunks": 4,
    "accuracy_graph_persist_enabled": False,
    "deep_policy_event_logging_enabled": False,
    "deep_policy_event_max_rows_per_run": 128,
    "deep_quality_event_logging_enabled": False,
    "subtitle_decision_explanation_logging_enabled": False,
    "background_prefetch_lora_enabled": False,
    "background_prefetch_lora_limit": 2,
    "background_prefetch_lora_retrieval_limit": 2,
    "background_prefetch_candidates_enabled": False,
    "background_prefetch_candidate_limit": 4,
    "background_prefetch_segment_limit": 4,
    "runtime_scheduler_ramp_up_enabled": True,
    "runtime_scheduler_ramp_initial_sec": 45.0,
    "runtime_scheduler_ramp_step_sec": 60.0,
    "runtime_scheduler_reserve_cores": 0,
    "runtime_monitor_terminal_log_enabled": False,
    "runtime_memory_monitor_interval_ms": 15000,
    "runtime_memory_disk_cache_budget_gb": 12.0,
    "runtime_memory_tracemalloc_enabled": False,
    "runtime_memory_tracemalloc_frames": 8,
    "macos_native_memory_snapshot_enabled": True,
    "macos_allocator_pressure_relief_enabled": True,
    "macos_allocator_pressure_relief_warning_mb": 64,
    "macos_allocator_pressure_relief_critical_mb": 256,
    "subtitle_generation_memory_guard_enabled": True,
    "subtitle_generation_memory_checkpoint_interval_ms": 3000,
    "subtitle_generation_gpu_trim_cooldown_sec": 8.0,
    "runtime_memory_warning_ratio": 0.20,
    "runtime_memory_critical_ratio": 0.12,
    "runtime_memory_warning_trim_cooldown_sec": 12.0,
    "runtime_memory_critical_trim_cooldown_sec": 6.0,
    "runtime_memory_warning_disk_trim_ratio": 0.72,
    "runtime_memory_critical_disk_trim_ratio": 0.45,
    "macos_memory_warning_reserve_gb": 3.0,
    "macos_memory_critical_reserve_gb": 1.5,
    "macos_memory_compressed_warning_ratio": 0.22,
    "macos_memory_compressed_critical_ratio": 0.30,
    "macos_memory_trim_runtime_caches_enabled": True,
    "macos_memory_cache_prune_enabled": True,
    "runtime_quality_self_review_enabled": False,
    "hardcase_training_queue_max_items_per_run": 48,
    "stt_backend_policy": "native",
    "cut_boundary_backend_policy": "native",
    "audio_extract_backend_policy": "native",
    "editor_render_backend_policy": "native",
    "whisperkit_native_auto_enabled": True,
    "codex_subtitle_native_fast_path_enabled": True,
    "codex_subtitle_native_fast_path_min_segments": 80,
    "codex_subtitle_native_fast_path_long_text_llm_ratio": 2.8,
    **autopilot_runtime_defaults(),
}


LORA_AUTO_MANAGED_SETTING_KEYS = frozenset(
    {
        "selected_audio_ai",
        "settings_simplified_ui_enabled",
        "simple_operation_mode",
        "simple_operation_mode_policy",
        "selected_vad",
        "selected_whisper_model",
        "selected_whisper_model_secondary",
        "selected_model",
        "selected_llm_provider",
        "stt_quality_preset",
        "stt_ensemble_enabled",
        "stt_ensemble_llm_judge_enabled",
        "stt_ensemble_llm_judge_require_risk",
        "stt_ensemble_llm_judge_local_only",
        "stt_ensemble_llm_judge_low_score_threshold",
        "stt_ensemble_llm_judge_min_score_delta",
        "stt_ensemble_llm_judge_max_similarity",
        "stt_selection_min_raw_candidate_similarity",
        "stt_selection_score_fallback_enabled",
        "stt_selection_score_fallback_min_score",
        "stt_selection_score_fallback_min_margin",
        "stt_ensemble_selective_enabled",
        "stt_ensemble_parallel_enabled",
        "stt_candidate_scoring_enabled",
        "stt_low_score_recheck_enabled",
        "stt_low_score_recheck_threshold",
        "stt_low_score_recheck_padding_sec",
        "stt_low_score_recheck_max_segments",
        "stt_low_score_recheck_max_audio_sec",
        "stt_recheck_native_fast_audio_filter_enabled",
        "stt_persistent_runtime_reuse_enabled",
        "stt_primary_fast_native_enabled",
        "stt_primary_fast_native_model",
        "stt_whisperkit_concurrent_workers",
        "stt_whisperkit_recheck_concurrent_workers",
        "stt_whisperkit_recheck_concurrent_max_workers",
        "stt_whisperkit_word_timestamp_concurrent_workers",
        "stt_whisperkit_concurrent_max_workers",
        "stt_whisperkit_native_allocator_can_raise_workers",
        "stt_whisperkit_gpu_saturation_max_workers",
        "stt_whisperkit_precision_aggressive_gpu_enabled",
        "stt_whisperkit_stream_results_enabled",
        "stt_whisperkit_native_compute_profile_enabled",
        "stt_whisperkit_compute_profile",
        "stt_worker_response_timeout_sec",
        "stt_worker_word_timestamp_response_timeout_sec",
        "stt_word_timestamp_worker_response_timeout_sec",
        "stt_word_timestamp_worker_straggler_timeout_sec",
        "stt_word_timestamp_worker_straggler_max_missing_chunks",
        "stt_word_timestamp_worker_straggler_min_received_ratio",
        "stt_word_timestamp_straggler_skip_enabled",
        "stt_recheck_worker_straggler_timeout_sec",
        "stt_recheck_worker_straggler_max_missing_chunks",
        "stt_recheck_worker_straggler_min_received_ratio",
        "stt_recheck_straggler_skip_enabled",
        "editor_live_stt_preview_follow_video_enabled",
        "editor_live_stt_preview_follow_interval_sec",
        "stt_word_timestamps_mode",
        "stt_word_timestamps_default_enabled",
        "stt_word_timestamps_precision_enabled",
        "stt_word_timestamps_precision_threshold",
        "stt_word_timestamps_precision_max_segments",
        "stt_word_timestamps_precision_max_audio_sec",
        "stt_word_timestamps_precision_keep_text",
        "stt_word_timestamps_precision_min_similarity",
        "stt_word_timestamps_precision_max_timing_shift_sec",
        "stt_word_timestamps_precision_min_duration_ratio",
        "stt_word_timestamps_precision_max_duration_ratio",
        "stt_missing_voice_min_duration_sec",
        "subtitle_quality_enabled",
        "subtitle_quality_auto_check_after_generate",
        "subtitle_quality_auto_correct_enabled",
        "editor_lora_runtime_enabled",
        "lora_pattern_index_enabled",
        "lora_pattern_first_enabled",
        "lora_pattern_autobuild_enabled",
        "lora_pattern_query_compact_enabled",
        "lora_pattern_skip_text_retrieval_score",
        "lora_store_full_text_enabled",
        "voice_lora_bridge_enabled",
        "voice_lora_audio_extraction_enabled",
        "stt1_adapter_audio_extraction_enabled",
        "deep_policy_pattern_only_enabled",
        "correction_memory_enabled",
        "wrong_answer_memory_enabled",
        "audio_chunk_routing_enabled",
        "audio_chunk_route_vad_enabled",
        "audio_chunk_route_max_workers",
        "audio_chunk_profile_sec",
        "whisper_chunk_overlap_sec",
        "llm_threads_auto_enabled",
        "llm_workers_auto_enabled",
        "runtime_hardware_acceleration_enabled",
        "apple_m_pipeline_parallel_enabled",
        "apple_m_chip_aware_scheduler_enabled",
        "apple_m_pipeline_respect_manual_worker_settings",
        "runtime_backend_autotune_enabled",
        "stt_backend_policy",
        "whisperkit_native_auto_enabled",
        "vad_backend_policy",
        "native_swift_vad_segments_enabled",
        "stt_apple_speech_challenger_enabled",
        "stt_apple_speech_vad_coupled_enabled",
        "stt_apple_speech_locale",
        "stt_apple_speech_benchmark_only",
        "cut_boundary_backend_policy",
        "audio_extract_backend_policy",
        "llm_backend_policy",
        "editor_render_backend_policy",
        "ffmpeg_videotoolbox_decode_enabled",
        "macos_native_app_store_target_enabled",
        "macos_native_require_xcode_tools",
        "runtime_performance_profile",
        "runtime_native_threads_auto_enabled",
        "runtime_native_threads",
        "runtime_native_json_enabled",
        "runtime_native_text_similarity_enabled",
        "runtime_native_cut_boundary_enabled",
        "mac_native_acceleration_enabled",
        "native_cpp_llm_macro_groups_enabled",
        "native_swift_quality_scoring_enabled",
        "native_swift_quality_scoring_min_segments",
        "native_swift_common_split_enabled",
        "native_swift_common_split_min_items",
        "runtime_memory_monitor_interval_ms",
        "runtime_memory_disk_cache_budget_gb",
        "runtime_memory_tracemalloc_enabled",
        "runtime_memory_tracemalloc_frames",
        "macos_native_memory_snapshot_enabled",
        "macos_allocator_pressure_relief_enabled",
        "macos_allocator_pressure_relief_warning_mb",
        "macos_allocator_pressure_relief_critical_mb",
        "subtitle_generation_memory_guard_enabled",
        "subtitle_generation_memory_checkpoint_interval_ms",
        "subtitle_generation_gpu_trim_cooldown_sec",
        "runtime_memory_warning_ratio",
        "runtime_memory_critical_ratio",
        "runtime_memory_warning_trim_cooldown_sec",
        "runtime_memory_critical_trim_cooldown_sec",
        "runtime_memory_warning_disk_trim_ratio",
        "runtime_memory_critical_disk_trim_ratio",
        "macos_memory_warning_reserve_gb",
        "macos_memory_critical_reserve_gb",
        "macos_memory_compressed_warning_ratio",
        "macos_memory_compressed_critical_ratio",
        "macos_memory_trim_runtime_caches_enabled",
        "macos_memory_cache_prune_enabled",
        "native_swift_llm_candidate_policy_enabled",
        "native_swift_deep_policy_enabled",
        "native_swift_lora_scoring_enabled",
        "native_swift_lora_scoring_min_docs",
        "ollama_python_client_enabled",
        "runtime_scheduler_auto_enabled",
        "scheduler_reduce_on_battery",
        "scheduler_reduce_on_user_input",
        "stt_workers_auto_enabled",
        "cut_pioneer_workers_auto_enabled",
        "cut_follower_workers_auto_enabled",
        "lora_workers_auto_enabled",
        "scan_cut_pioneer_workers",
        "scan_cut_verify_workers",
        "scan_cut_pioneer_cpu_max_workers",
        "scan_cut_follower_cpu_max_workers",
        "scan_cut_follower_outer_splits",
        "scan_cut_pioneer_worker_overlap_steps",
        "scan_cut_cv2_threads_per_worker",
        "scan_cut_cv2_video_backend",
        "scan_cut_provisional_sample_step_sec",
        "scan_cut_long4k_provisional_sample_step_sec",
        "scan_cut_no_proxy_pioneer_max_samples",
        "scan_cut_no_proxy_min_sample_step_sec",
        "scan_cut_provisional_compare_max_width",
        "scan_cut_provisional_compare_max_height",
        "scan_cut_pioneer_packet_scout_enabled",
        "scan_cut_pioneer_packet_scout_timeout_sec",
        "scan_cut_pioneer_packet_scout_raw_candidates",
        "scan_cut_pioneer_packet_delta_threshold",
        "scan_cut_pioneer_packet_mad_multiplier",
        "scan_cut_pioneer_pipe_enabled",
        "scan_cut_pioneer_pipe_hwaccel_enabled",
        "scan_cut_pioneer_pipe_fps",
        "scan_cut_pioneer_pipe_width",
        "scan_cut_pioneer_pipe_height",
        "scan_cut_pioneer_pipe_dense_flow_enabled",
        "scan_cut_pioneer_pipe_flow_width",
        "scan_cut_pioneer_pipe_pixel_threshold",
        "scan_cut_pioneer_pipe_pixel_strong_threshold",
        "scan_cut_pioneer_pipe_flow_residual_threshold",
        "scan_cut_pioneer_pipe_timeout_sec",
        "scan_cut_pioneer_pipe_max_candidates",
        "scan_cut_pioneer_min_gap_sec",
        "scan_cut_pioneer_dense_flow_confirm_enabled",
        "scan_cut_pioneer_strict_multiplier",
        "scan_cut_pioneer_candidate_fusion_enabled",
        "scan_cut_pioneer_fusion_window_sec",
        "scan_cut_pioneer_fusion_max_candidates",
        "scan_cut_follower_stream_start_percent",
        "scan_cut_follower_stream_batch_size",
        "scan_cut_follower_stream_min_interval_sec",
        "llm_threads_resource_max",
        "roughcut_llm_threads_auto_enabled",
        "roughcut_llm_threads_resource_max",
        "roughcut_llm_rows_auto_enabled",
        "roughcut_llm_rows_lora_enabled",
        "roughcut_llm_rows_lora_blend",
        "roughcut_llm_rows_exploration_rate",
        "roughcut_llm_max_context_rows",
        "roughcut_llm_chunk_rows",
        "roughcut_llm_lookahead_rows",
        "roughcut_llm_context_min_rows",
        "roughcut_llm_context_max_rows",
        "roughcut_llm_chunk_min_rows",
        "roughcut_llm_chunk_max_rows",
        "roughcut_llm_lookahead_min_rows",
        "roughcut_llm_lookahead_max_rows",
        "roughcut_codex_timeout_sec",
        "roughcut_codex_max_context_rows",
        "roughcut_codex_chunk_rows",
        "roughcut_codex_lookahead_rows",
        "chunk_time_limit",
        "subtitle_bundle_autopilot_enabled",
        "subtitle_bundle_lora_enabled",
        "subtitle_bundle_lora_blend",
        "subtitle_bundle_target_sec",
        "subtitle_bundle_min_sec",
        "subtitle_bundle_max_sec",
        "subtitle_bundle_use_confirmed_cuts",
        "subtitle_bundle_use_provisional_cuts",
        "subtitle_bundle_confirmed_cut_min_sec",
        "subtitle_bundle_provisional_cut_min_sec",
        "subtitle_bundle_boundary_snap_window_sec",
        "subtitle_cut_boundary_guard_enabled",
        "subtitle_cut_boundary_allow_high_confidence_crossing",
        "subtitle_cut_boundary_high_confidence_score",
        "deep_subtitle_policy_enabled",
        "deep_segment_setting_policy_enabled",
        "deep_subtitle_reranker_enabled",
        "deep_subtitle_reranker_min_margin",
        "deep_stt_candidate_selector_enabled",
        "deep_stt_candidate_min_score",
        "deep_stt_candidate_min_margin",
        "deep_timing_adjustment_enabled",
        "deep_timing_max_shift_sec",
        "subtitle_timing_fusion_enabled",
        "subtitle_timing_fusion_max_shift_sec",
        "subtitle_timing_fusion_word_weight",
        "subtitle_timing_fusion_vad_weight",
        "subtitle_timing_fusion_lora_duration_weight",
        "subtitle_timing_fusion_boundary_snap_window_sec",
        "deep_sequence_smoothing_enabled",
        "deep_sequence_max_shift_sec",
        "deep_sequence_bridge_gap_sec",
        "deep_segment_setting_exploration_rate",
        "deep_policy_event_logging_enabled",
        "deep_policy_event_max_rows_per_run",
        "deep_policy_hard_case_margin",
        "deep_hard_case_mining_enabled",
        "hardcase_training_queue_enabled",
        "hardcase_training_queue_max_items_per_run",
        "stt_lattice_selector_enabled",
        "stt_lattice_min_confidence",
        "stt_lattice_replace_margin",
        "stt_lattice_min_match_score",
        "stt_selection_min_raw_candidate_similarity",
        "stt_selection_score_fallback_enabled",
        "stt_selection_score_fallback_min_score",
        "stt_selection_score_fallback_min_margin",
        "stt_lattice_require_word_timestamps",
        "stt_lattice_persist_enabled",
        "stt_lattice_artifact_candidate_limit",
        "stt_lattice_artifact_word_limit",
        "llm_candidate_policy_enabled",
        "llm_candidate_policy_max_candidates",
        "llm_candidate_policy_allow_minimal_edit",
        "llm_candidate_policy_max_edit_ratio",
        "subtitle_llm_macro_chunk_enabled",
        "subtitle_llm_macro_chunk_min_rows",
        "subtitle_llm_macro_chunk_max_rows",
        "subtitle_llm_macro_chunk_use_cut_boundaries",
        "subtitle_llm_prev_next_context_enabled",
        "subtitle_llm_context_candidate_limit",
        "subtitle_llm_context_min_current_similarity",
        "subtitle_llm_context_neighbor_reject_margin",
        "subtitle_llm_context_boundary_refine_enabled",
        "subtitle_llm_context_word_correction_enabled",
        "subtitle_llm_context_max_pairs",
        "subtitle_llm_context_require_risk_signal",
        "subtitle_llm_context_max_pair_gap_sec",
        "subtitle_llm_context_min_pair_chars",
        "subtitle_llm_context_max_pair_chars",
        "subtitle_llm_context_allow_merge",
        "subtitle_llm_context_merge_max_chars",
        "subtitle_llm_context_merge_micro_max_chars",
        "subtitle_llm_context_merge_micro_max_duration_sec",
        "subtitle_llm_context_max_word_corrections",
        "subtitle_llm_context_timeout_sec",
        "subtitle_llm_context_num_predict",
        "subtitle_llm_text_only_timing_lock_enabled",
        "subtitle_final_stt_slot_order_guard_enabled",
        "subtitle_native_prepass_workers",
        "subtitle_native_prepass_workers_resource_max",
        "codex_subtitle_native_fast_path_enabled",
        "codex_subtitle_native_fast_path_min_segments",
        "codex_subtitle_native_fast_path_long_text_llm_ratio",
        "linebreak_lora_policy_enabled",
        "linebreak_lora_policy_max_patterns",
        "subtitle_target_line_count",
        "subtitle_target_line_count_auto_enabled",
        "llm_confidence_gate_enabled",
        "llm_confidence_gate_min_lora_score",
        "llm_confidence_gate_max_compact_ratio",
        "llm_confidence_gate_strong_signal_score",
        "llm_confidence_gate_strong_max_compact_ratio",
        "llm_confidence_gate_strong_max_duration_ratio",
        "llm_minimize_enabled",
        "llm_minimize_min_gate_confidence",
        "llm_minimize_required_signal_score",
        "llm_verifier_enabled",
        "llm_verifier_min_similarity",
        "llm_verifier_max_length_delta_ratio",
        "llm_verifier_short_text_compact_len",
        "llm_verifier_long_text_compact_len",
        "llm_verifier_short_text_max_length_delta_ratio",
        "llm_verifier_long_text_max_length_delta_ratio",
        "llm_verifier_short_duration_sec",
        "llm_verifier_long_duration_sec",
        "llm_verifier_short_duration_delta_adjust",
        "llm_verifier_long_duration_delta_adjust",
        "llm_verifier_max_chunks",
        "llm_verifier_preserve_numbers",
        "llm_verifier_preserve_proper_nouns",
        "llm_verifier_preserve_interjections",
        "llm_verifier_block_added_content_tokens",
        "accuracy_decision_graph_enabled",
        "accuracy_graph_persist_enabled",
        "subtitle_accuracy_metrics_enabled",
        "subtitle_output_selector_enabled",
        "subtitle_context_consistency_enabled",
        "subtitle_context_repeat_window_sec",
        "subtitle_context_near_duplicate_ratio",
        "subtitle_context_cps_jump_ratio",
        "subtitle_context_score_penalty_weight",
        "subtitle_context_repair_enabled",
        "subtitle_context_repair_drop_repeats",
        "subtitle_context_repair_drop_empty_enabled",
        "subtitle_context_repair_drop_hallucinations_enabled",
        "subtitle_context_repair_overlap_pad_sec",
        "subtitle_context_repair_min_duration_sec",
        "subtitle_context_repair_cps_jumps_enabled",
        "subtitle_context_repair_cps_max_extend_sec",
        "subtitle_lora_style_consistency_enabled",
        "subtitle_lora_style_min_profile_score",
        "subtitle_lora_style_max_length_drift_ratio",
        "subtitle_lora_style_max_line_drift",
        "subtitle_lora_style_max_cps_ratio",
        "subtitle_lora_style_score_penalty_weight",
        "subtitle_lora_micro_merge_enabled",
        "subtitle_lora_micro_merge_min_duration",
        "subtitle_lora_micro_merge_gap_sec",
        "subtitle_lora_micro_merge_word_gap_sec",
        "subtitle_lora_micro_merge_continuous_sec",
        "editor_truth_capture_enabled",
        "editor_truth_capture_min_chars",
        "editor_truth_capture_max_chars",
        "editor_truth_runtime_apply_enabled",
        "editor_truth_runtime_min_similarity",
        "editor_truth_runtime_pattern_limit",
        "user_edit_metrics_enabled",
        "user_edit_metrics_deep_event_enabled",
        "user_edit_metrics_hard_case_score",
        "user_edit_metrics_text_ratio_hard",
        "user_edit_metrics_timing_shift_hard_sec",
        "runtime_quality_self_review_enabled",
        "deep_quality_event_logging_enabled",
        "deep_quality_event_all_segments",
        "deep_quality_event_min_score",
        "subtitle_decision_explanation_logging_enabled",
        "uncertainty_first_enabled",
        "uncertainty_first_process_order",
        "uncertainty_first_easy_score",
        "uncertainty_first_precision_score",
        "uncertainty_first_easy_signal_score",
        "uncertainty_first_low_stt_score",
        "uncertainty_first_low_lora_score",
        "uncertainty_first_long_text_ratio",
        "deep_runtime_adaptation_enabled",
        "deep_runtime_adaptation_min_events",
        "deep_runtime_adaptation_lookback_events",
        "deep_runtime_adaptation_rate",
        "continuous_threshold",
        "gap_push_rate",
        "gap_pull_rate",
        "single_subtitle_end",
        "split_length_threshold",
        "subtitle_common_split_guard_enabled",
        "subtitle_common_split_target_chars",
        "subtitle_common_split_hard_max_chars",
        "subtitle_common_split_hard_max_duration_sec",
        "subtitle_target_line_count",
        "subtitle_target_line_count_auto_enabled",
        "sub_min_duration",
        "sub_max_duration",
        "sub_max_cps",
        "sub_dedup_window",
        "stt_window_drift_report_enabled",
        "sub_gap_break_sec",
        "review_auto_correct_apply_threshold",
        "review_auto_correct_min_improvement",
        "review_recheck_buffer_sec",
        "review_vad_before_stt_enabled",
        "review_vad_strict_mode",
        "review_vad_speech_pad_sec",
        "review_vad_min_silence_sec",
        "vad_post_stt_align_enabled",
        "vad_post_stt_max_shift_sec",
        "vad_post_stt_edge_pad_sec",
        "vad_voice_start_priority_max_stt_lead_sec",
        "vad_threshold",
        "vad_min_speech",
        "vad_min_silence",
        "vad_speech_pad",
        "vad_window_size",
        "ten_vad_threshold",
        "ten_vad_hop_size",
        "df_hp",
        "df_eq_g",
        "df_comp_th",
        "df_vol",
        "df_atten_lim",
        "w_df_no_speech",
        "w_df_logprob",
        "w_df_comp",
        "w_df_temp_max",
        "w_none_no_speech",
        "w_none_logprob",
        "w_none_comp",
        "w_none_temp_max",
        "w_beam_size",
        "w_patience",
        "w_length_penalty",
        "ff_threads",
        "ff_ac",
        "ff_ar",
        "ff_hp",
        "ff_lp",
        "ff_nf",
        "ff_chunk",
        "ff_dynaudnorm_m",
        "ff_dynaudnorm_p",
        "ff_treble_boost",
        "none_hp",
        "none_lp",
        "none_nf",
        "none_target",
        "none_comp_th",
        "none_vol",
        "roughcut_llm_model",
        "roughcut_llm_provider",
        "roughcut_llm_rows_auto_enabled",
        "roughcut_llm_rows_lora_enabled",
        "roughcut_llm_rows_lora_blend",
        "roughcut_llm_rows_exploration_rate",
        "roughcut_llm_max_context_rows",
        "roughcut_llm_chunk_rows",
        "roughcut_llm_lookahead_rows",
        "roughcut_llm_context_min_rows",
        "roughcut_llm_context_max_rows",
        "roughcut_llm_chunk_min_rows",
        "roughcut_llm_chunk_max_rows",
        "roughcut_llm_lookahead_min_rows",
        "roughcut_llm_lookahead_max_rows",
        "roughcut_codex_timeout_sec",
        "roughcut_codex_max_context_rows",
        "roughcut_codex_chunk_rows",
        "roughcut_codex_lookahead_rows",
        "cut_boundary_level",
        "scan_cut_boundary_level",
        "scan_cut_level",
        "scan_cut_auto_sample_step_sec",
        "scan_cut_auto_threshold",
        "scan_cut_threshold",
        "scan_cut_audio_gain_enabled",
        "scan_cut_audio_spectral_flux_enabled",
        "scan_cut_audio_spectral_flux_window_sec",
        "scan_cut_audio_spectral_flux_threshold_multiplier",
        "scan_cut_use_preview_proxy_enabled",
        "scan_cut_pioneer_sequential_decode_enabled",
        "scan_cut_follower_dense_flow_enabled",
        "scan_cut_dense_flow_backend",
        "scan_cut_dense_flow_sequential_window_decode_enabled",
        "scan_cut_dense_flow_window_radius",
        "scan_cut_dense_flow_width",
        "scan_cut_dense_flow_diff_threshold",
        "scan_cut_dense_flow_min_diff",
        "scan_cut_dense_flow_strong_diff",
        "scan_cut_dense_flow_min_motion_px",
        "scan_cut_dense_flow_motion_residual_ratio",
        "scan_cut_dense_flow_motion_coherence",
        "scan_cut_dense_flow_min_coverage",
        "scan_cut_dense_flow_motion_score_threshold",
        "scan_cut_dense_flow_motion_votes_required",
        "scan_cut_dense_flow_hard_cut_residual_ratio",
        "scan_cut_dense_flow_fade_trend_protection_enabled",
        "scan_cut_dense_flow_fade_brightness_range",
        "scan_cut_dense_flow_fade_motion_max_px",
        "scan_cut_dense_flow_brightness_trend_epsilon",
        "scan_cut_audio_gain_threshold_db",
        "scan_cut_audio_gain_window_sec",
        "scan_cut_audio_gain_min_gap_sec",
        "scan_cut_audio_spectral_flux_enabled",
        "scan_cut_audio_spectral_flux_window_sec",
        "scan_cut_audio_spectral_flux_threshold_multiplier",
        "scan_cut_pioneer_candidate_fusion_enabled",
        "scan_cut_pioneer_fusion_window_sec",
        "scan_cut_pioneer_fusion_max_candidates",
        "scan_cut_ffmpeg_scene_prepass_enabled",
        "scan_cut_ffmpeg_scene_replace_opencv_enabled",
        "scan_cut_ffmpeg_scene_threshold",
        "scan_cut_ffmpeg_scene_timeout_sec",
        "scan_cut_ffmpeg_scene_max_candidates",
        "roughcut_boundary_fusion_enabled",
        "cut_boundary_fusion_window_sec",
        "cut_boundary_fusion_keep_threshold",
        "cut_boundary_fusion_verify_threshold",
        "roughcut_context_shift_boundary_threshold",
        "roughcut_context_shift_min_gap_sec",
        "deep_cut_boundary_model_enabled",
        "deep_cut_boundary_keep_threshold",
        "deep_cut_boundary_verify_threshold",
    }
)


def custom_defaults_path(dataset_dir: str | None = None) -> str:
    return os.path.join(dataset_dir or config.DATASET_DIR, "custom_defaults.json")


def folder_settings_path(dataset_dir: str | None = None) -> str:
    return os.path.join(dataset_dir or config.DATASET_DIR, "folder_settings.json")


def load_custom_defaults(dataset_dir: str | None = None) -> dict[str, Any]:
    path = custom_defaults_path(dataset_dir)
    data = read_json_file(path, default={}, expected_type=dict, context="custom_defaults", log_errors=False)
    return dict(data) if isinstance(data, dict) else {}


def load_folder_settings(dataset_dir: str | None = None) -> dict[str, Any]:
    path = folder_settings_path(dataset_dir)
    data = read_json_file(path, default={}, expected_type=dict, context="folder_settings", log_errors=False)
    return dict(data) if isinstance(data, dict) else {}


def hardcoded_default_settings(
    *,
    dataset_dir: str | None = None,
    include_custom_defaults: bool = True,
    include_folder_settings: bool = True,
) -> dict[str, Any]:
    out: dict[str, Any] = {}
    out.update(deepcopy(UI_ENGINE_DEFAULTS))
    out.update(deepcopy(getattr(config, "DEFAULT_ADV_SETTINGS", {}) or {}))
    out.update(deepcopy(getattr(config, "DEFAULT_ROUGHCUT_SETTINGS", {}) or {}))
    out.update(deepcopy(CUT_BOUNDARY_DEFAULTS))
    out.update(deepcopy(PATH_SETTING_DEFAULTS))
    out.update(deepcopy(LLM_PROMPT_DEFAULTS))
    if include_folder_settings:
        out.update(load_folder_settings(dataset_dir))
    if include_custom_defaults:
        out.update(load_custom_defaults(dataset_dir))
    return out


def materialize_user_settings(
    settings: dict[str, Any] | None = None,
    *,
    dataset_dir: str | None = None,
) -> dict[str, Any]:
    input_settings = dict(settings or {}) if isinstance(settings, dict) else {}
    input_model = str(input_settings.get("selected_model", "") or "").strip()
    input_has_user_llm = bool(
        "selected_model" in input_settings
        and input_model
        and "사용 안함" not in input_model
        and "subtitle_llm_user_selected" not in input_settings
    )
    out = hardcoded_default_settings(dataset_dir=dataset_dir)
    if input_settings:
        out.update(deepcopy(input_settings))
    if bool(out.get("roughcut_llm_enabled", False)):
        # 러프컷 자동 실행 토글은 현재 별도 UI 제어가 없어서 레거시 False 기본값이 남기 쉽다.
        # 러프컷 LLM을 사용하는 프로젝트는 생성 완료 후 자동 실행되도록 저장값도 함께 보정한다.
        out["roughcut_run_after_subtitle_generation"] = True
    out = sanitize_persisted_settings(out)
    if input_has_user_llm:
        out["subtitle_llm_user_selected"] = True
    out["user_prompt"] = ""
    out["llm_prompt"] = ""
    out["editor_roughcut_draft_prompt"] = ""
    out["roughcut_llm_prompt"] = ""
    out["default_llm_prompt"] = str(getattr(config, "DEFAULT_LLM_PROMPT", ""))
    out["_settings_schema"] = USER_SETTINGS_SCHEMA
    out["_settings_storage"] = "dataset/user_settings.json"
    out["_auto_managed_by_lora"] = sorted(LORA_AUTO_MANAGED_SETTING_KEYS)
    simple_mode = selected_mode_from_settings(out)
    out = apply_mode_scope_quality(out, simple_mode)
    if simple_mode == "auto":
        out.update(deepcopy(SPEED_SAFE_AUTO_DEFAULTS))
        out = apply_mode_scope_quality(out, "auto")
        out["_speed_safe_auto_profile"] = SPEED_SAFE_AUTO_PROFILE_VERSION
    out = apply_mode_runtime_settings(apply_autopilot_runtime_policy(out))
    return materialize_automatic_speaker_settings(out)


def sanitize_persisted_settings(settings: dict[str, Any] | None = None) -> dict[str, Any]:
    if not isinstance(settings, dict):
        return {}
    sanitized = dict(settings)
    for key in PERSISTED_SECRET_SETTING_KEYS:
        sanitized.pop(key, None)
    return sanitized


def is_lora_auto_managed_setting(key: str) -> bool:
    return str(key or "") in LORA_AUTO_MANAGED_SETTING_KEYS


__all__ = [
    "PERSISTED_SECRET_SETTING_KEYS",
    "LORA_AUTO_MANAGED_SETTING_KEYS",
    "USER_SETTINGS_SCHEMA",
    "custom_defaults_path",
    "folder_settings_path",
    "hardcoded_default_settings",
    "is_lora_auto_managed_setting",
    "load_custom_defaults",
    "load_folder_settings",
    "materialize_user_settings",
    "sanitize_persisted_settings",
]
